### ISSUE TITLE
게시판 추가 기능

### ISSUE THREAD

**Issue by aeroitems** [netnamu/zinpack#10]
뉴스와 같은 형태로 분리된 게시판 추가 기능 필요

**Comment by aeroitems** [comment]
그룹을 오픈모드로 변경할 수 있다면 이 기능을 대신 할 수 있는 것은 아닌지?
아니면 서브 리스트 에서도 메인 처럼 광고와 메인슬라이드를 계속 넣어야 하는 것인지?

**Comment by jejoongkim** [comment]
그룹을 오픈모드로 볼 수 있도록 한 것은 적용이 되었고
그룹 가입 과정도 가입과정 없슴 옵션이 있어야 할 듯 합니다.
그나마 한번 더 가입하는 것도 필요 없을 듯 합니다. 그렇게 되면 게시판 추가 기능 없이 그룹으로 그냥 게시판을 활용할 수 있습니다.

**Comment by aeroitems** [comment]
게시판 추가 기능은 별도로 협의를 해야할 사안으로 보입니다. 
9/24 과 9/25 에 이에 대한 협의를 하도록 하겠습니다.
