### ISSUE TITLE
본문을 보고 나서...목록 단추가 사라졌습니다.

### ISSUE THREAD

**Issue by jejoongkim** [netnamu/zinpack#100]
본문 기사를 위에서 부터 아래로..쭉 읽고 나서...

있던 목록 버튼이 사라졌습니다.

**Comment by baemoc** [comment]
상단메뉴 작업하면서 카테고리가 변경되어 잠시 숨겨놨습니다.
다음 버전에 노출되도록 하겠습니다.

**Comment by jejoongkim** [comment]
아 그랬군요~ 알겠습니다
