### ISSUE TITLE
메인슬라이드 위에 메인슬라이드를 등록하면 2중으로 이미지가 나타나는 증상

### ISSUE THREAD

**Issue by aeroitems** [netnamu/zinpack#101]
이미 설정되어 있는 메인슬라이드 상단에 다시 메인슬라이드를 하나더 설정하면 상단 메인 슬라이드가 2중으로 나타나는 증상이 있습니다.

**Comment by baemoc** [comment]
슬라이드마다 적용되는 변수가 동일하여 오류가 발생하였습니다.
변수를 초기화하여 해결.
