### ISSUE TITLE
zinpack.com 설치관련

### ISSUE THREAD

**Issue by baemoc** [netnamu/zinpack#102]
시행착오 끝에 admin은 나오게 해놨습니다.
그런데 사이트는 제대로 안나오네요.
최효탁 이사님께서 확인해주시면 감사하겠습니다.

**Comment by baemoc** [comment]
제가 Rewrite 모듈( URL을 관리모듈)을 적용한 방법 적어놓습니다.
1. 아파치의 httpd.conf 파일의 rewrite 모듈이 활성화 되어있는지 확인.
   ////////////////////////////////
   LoadModule rewrite_module   modules/mod_rewrite.so
   ////////////////////////////////
   (앞에 #이 붙어있으면 주석처리되므로 #만 제거.)
2. phpinfo() 를 실행시켜  mod_rewrite 검색 후, 확인.
   (Loaded Modules 안에 있음.)
3. 아파치의 httpd.conf 파일의 <Directory> 안에 있는 값 수정.
   ////////////////////////////////
   <Directory />
   Options FollowSymLinks
   AllowOverride All
   </Directory>
   ////////////////////////////////
   (<Directory> 에 경로가 붙어 있는 등.. <Directory> 가 여러개 있는 경우, 내부의 값을 전부 변경해주어야 함.)
4. 기타 추가사항(.htaccess 안에 존재해야 하는 것들)
   ////////////////////////////////
   RewriteEngine On 
   RewriteBase /
   RewriteRule (여러가지 방식으로 사용가능)
   ////////////////////////////////

**Comment by leihaht** [comment]
서버 설정이 이제야 잘 되나보네요.
다시 설치하고 난뒤에 잘 됩니다.

감사합니다.

**Comment by leihaht** [comment]
혹시 나중을 위해 도움이 될만한 리눅스에서의 설치 가이드 입니다.
http://blog.4digits.net/getting-started-with-processwire/

**Comment by baemoc** [comment]
서버마다 경로 및 설정값 들이 상이하기 때문에
설치가이드 만으로는 설명이 부족합니다.
