### ISSUE TITLE
php5.3.28 업그레이드 및 서버이전

### ISSUE THREAD

**Issue by baemoc** [netnamu/zinpack#103]
php 업그레이드로 인한 버그들 수정.

서버이전 시, 4시간정도 소요예정.
새벽에 작업하도록 하겠습니다.

**Comment by baemoc** [comment]
1. PHP5.3 에서 ereg_replace() 없어짐
   preg_replace() 로 대체
2. $HTTP_POST_VARS 사용을 위한 설정
   php.ini 에서
   register_long_arrays = On
3. 업로드 크기 제한
   php.ini 에서
   upload_max_filesize = 200M
   post_max_size = 200M
   memory_limit = 200M
4. imagick 라이브러리 설치
   Imagick
   ImagickDraw
   ImagickPixel
   ImagickPixelIterator
   http://kr1.php.net/manual/en/book.imagick.php

**Comment by baemoc** [comment]
기존에 사용하던 서버는 해지처리 되었고,
사용기간을 현재서버에 추가하였습니다.

**Comment by aeroitems** [comment]
현재 버전이 2.5 의 기준이 되며 빌드 번호는 001로 시작합니다.
다음번 버전은 자동으로 2.5.2 부터 시작합니다.
