### ISSUE TITLE
UI 컬러지정 기능

### ISSUE THREAD

**Issue by aeroitems** [netnamu/zinpack#104]
메뉴와 기타 UI 요소들의 컬러를 사이트 관리자가 임의로 지정하는 기능이 필요합니다.

최이사님께서 사이트의 테마를 변경할 때 사용하는 구성요소를 알려주시면 배이사님이 작업하시기 수월하다고 하시는데 어떤 요소들을 주고 받아야할지 두분의 회의가 필요할 것으로 보여집니다.

배이사님이 본 이슈에 회의 사항을 올려주시거나 카톡등으로 협의 하시기를 요청합니다.

**Comment by baemoc** [comment]
테마에서 사용되는 class들을 알려주시고 어느부분에 적용되는지 알려주시면 감사하겠습니다.

**Comment by leihaht** [comment]
$colorset: (
  default:   #fff,
  primary:   #428bca,
  success:   #5cb85c,
  info:      #5bc0de,
  warning:   #f0ad4e,
  danger:    #d9534f,

  blue:            #57889c,
  blueLight:       #92a2a8,
  blueDark:        #4c4f53,
  teal:            #568a89,
  green:           #356e35,
  greenDark:       #496949,
  greenLight:      #71843f,
  purple:          #6e587a,
  magenta:         #6e3671,
  pink:            #ac5287,
  pinkDark:        #a8829f,
  yellow:          #b09b5b,
  orange:          #c79121,
  red:             #a90329,
  redLight:        #a65858,

  transparent:     transparent,
  theme:           #428bca
) !default;

css의 preprocessing의 scss 변수중 하나입니다.
여기에 이미 등록이 되있기에 여기에 있는것을 그대로 쓰면되구요.

적용방법은
box의 class에서 br-default나, br-theme 등등 이런것이 있을겁니다.
그걸 br-색 이렇게 바꾸시면 되요.

**Comment by baemoc** [comment]
br-색은 의미가 없습니다. 관리자가 색상값을 자유롭게 선택해야 합니다.
아래와 같은 요소들을 알아야 합니다.
.zinpack-style-1 .br-default{background:#fff;color:#585858}
.zinpack-style-1 .br-default.box-link:hover{background:#e6e6e6}
.zinpack-style-1 .br-default p{color:#999}

**Comment by leihaht** [comment]
br-색
이건 색값을 지정해서 쓸수있게 제가 미리 만들어둔거구요.
그외의 색을 지정하시려면 직접 css를 적용하셔야죠.

정확히 어떤것을 물어보시는지 알수가 없군요.

**Comment by leihaht** [comment]
테마 요소들의 css를 변경하시는것이라면 css를 직접 만드셔야됩니다.

**Comment by leihaht** [comment]
새로운 테마를 만드시는것을 말씀하시는것이라면,
css의 preprocessing의 원본 소스를 만들어서 css로 컴파일해야됩니다.

**Comment by baemoc** [comment]
말씀하셨듯이 테마의 요소들을 알고 싶습니다.
class별로 색상값을 입력 받아서 DB에 저장후, CSS의 class 컬러값으로 출력할 예정입니다.
이미 만들어주신 테마들은 DB에 저장하여 기본적으로 선택할 수 있게 할것이고,
추가적으로 사이트관리자나 일반유저들이 테마를 만들수 있도록 할 예정입니다.
제가 직접 매페이지의 UI요소마다 컬러값을 넣기에는 너무 많은 작업을 해야 합니다.
그래서 지금 쓰이고 있는 테마 내부의 class들을 알면 작업하기가 편하겠습니다.
.zinpack-style-1 <-- 이건 테마의 class인걸로 알고 있습니다.
그안에 종속된 class(아래와 같은 class)들을 알아야하고, 그 사용범위도 알아야 합니다.
.br-default (예/ 본문 박스 - background, color)
.br-default .box-link:hover (예/ 본문 박스 안의 링크의 마우스오버 - background)
.br-default p (예/ 본문박스의 p태그 - color)

**Comment by baemoc** [comment]
일단 생각해본 내용입니다.
사이트관리자는 테마를 유/무료로 구입하거나 제작할 수 있습니다.
제작한 테마는 CSS파일이 아닌 DB에 저장이 됩니다.
사이트관리자는 구입하거나 제작한 테마를 목록으로 가질수 있습니다.
사이트관리자가 목록에서 테마를 선택하여 적용을 하면 CSS파일이 만들어집니다.
존재하는 CSS가 있다면 기존에 있던 CSS파일에 새로운 CSS파일을 덮어 씌웁니다.
사이트별로 현재 적용되어 있는 테마의 UI색상값을 자유롭게 변경할 수 있습니다.
색상값이 변경되면 기존에 있던 CSS파일에 새로운 CSS파일을 덮어 씌웁니다.

////////추가할 페이지
사이트관리자 페이지 내부에 테마를 사고파는 페이지
사이트의 UI들의 색상을 변경하는 페이지(사이트에 적용하기 버튼, 테마로 추가하기 버튼)
제작한 테마 리스트 페이지
판매 내역 페이지
구매 내역 페이지
기존과 같이 테마 선택하는 곳에서 미리보기 및 적용 가능

//////////추가할 DB 테이블
테마 상품 table - 테마명, 스크린샷, 가격, UI별 적용 색상 등
판매 table
사이트별 현재 적용된 UI색상  table

**Comment by baemoc** [comment]
제가 일일이 확인해서 진행하도록 하겠습니다.

**Comment by leihaht** [comment]
테마 제작에 관해서는 이미 zinpack 3.0에서 논의 됬던건데요.
현재 zinapck 2.5에서 적용하려면 배이사님이 많은 작업을 해주셔야됩니다.

테마 적용되는것은 html 코딩을 보시면 더욱 자세히 알수있구요.
현재 github에서 논의 되는것들은 전부 공개되는것이라서 소스 코드를 여기에서 논의 할수는 없습니다.

**Comment by baemoc** [comment]
기존과 같이 사이트 상단 우측의 테마버튼을 통해 테마 변경이 가능합니다.
테마를 변경하면, 사이트DB에 테마의 값들이 저장됩니다.
각각의 값들은 관리자 > 다자인 설정 > 테마디자인 설정 에서 변경가능합니다.

**Comment by jejoongkim** [comment]
테마 버튼을 통한 손쉬운 변경
각 각의 개별 조정을 통한 변경 테스트 완료 했습니다.
