### ISSUE TITLE
모바일에서 사진 업로드시 리사이즈

### ISSUE THREAD

**Issue by aeroitems** [netnamu/zinpack#105]
모바일에서 사진을 업로드할때 필요 이상으로 큰 사진을 업로드하게 됩니다.
이 사진을 자동으로 줄여서 등록하도록 했으면 합니다.
제가 생각하는 방안으로는 
1. 관리자에게 게시판 생성시 리사이즈 옵션을 줄 수 있도록 한다.
2. 모바일의 경우 무조건 리사이즈 한다(가로 1000 이상일 경우 무조건 1000으로 압축율은 50% 이하로/1000 이하의 사진이라도 압축율을 50%로 강제 조절 저장).
3. 위의 두가지를 적절하게 섞는다.

의견 주시기 바랍니다.

**Comment by baemoc** [comment]
가로 1100에 100%로 하면 100kb 정도 됩니다.

**Comment by baemoc** [comment]
가로 1100 이상일 경우 1100으로 줄이고, 압축율 50으로 셋팅했습니다.

**Comment by baemoc** [comment]
에디터로 이미지 등록시에도 가로사이즈가 1100 초과되면 1100으로 줄이고, 압축율 50으로 업로드 됩니다.
