### ISSUE TITLE
회원 가입 간소화

### ISSUE THREAD

**Issue by aeroitems** [netnamu/zinpack#106]
회원의 유입을 증가 시키기 위해 간소화한 회원 가입을 필요로 합니다.
1. 최소 요구 사항 정의 필요 -  ID와 PW 그외 추가 되어야할 최소 사항
2. 추가 사항의 입력 시기 지정 필요 - 그외 추가 입력 사항을 입력하는 곳과 필수 입력 시점의 지정

이에 대한 의견 부탁드립니다.

**Comment by baemoc** [comment]
1. 이메일(아이디), 비밀번호, 닉네임,이름 만 회원정보에 저장!
2. 쇼핑몰 주문시 주소, 전화번호 저장!

**Comment by baemoc** [comment]
회원가입 폼에서 이용약관, 회원정보취급방침 안나오는 오류 수정함.

**Comment by baemoc** [comment]
쇼핑몰 주문시 구매자정보를 직접 입력하도록 변경.
회원정보의 추가정보가 없을 경우, 구매자정보의 핸드폰번호와 배송주소를 저장함.
