### ISSUE TITLE
본문의 스크래퍼를 본문의 사이드로 배치하는 기능

### ISSUE THREAD

**Issue by baemoc** [netnamu/zinpack#110]
사이드의 영역은 어떻게 할것인지? (쇼핑,컨텐츠,이북도 고려하여 생각해 주십시오.)
1 본문에 들어가는 타이틀영역,본문영역,소셜영역의 사이드에 위치
2 타이틀,소셜을 제외한 본문영역의 사이드에 위치
![scrap](https://cloud.githubusercontent.com/assets/8477739/5139547/baba31c8-71a2-11e4-80fe-bcf4f5b0e6d4.jpg)

좌/우 사이드 선택 가능하게 할것인지?
본문의 가로사이즈도 변경이 가능하게 할것인지?
본문의 가로사이즈가 변경이 가능하다면, 사이트에 일괄 적용할 것인지? 상단메뉴별로 적용할 것인지?
기존 스크래퍼를 사이드로 올리고 하단까지 이어지게 할것인지? 사이드에 놓일 스크래퍼를 따로 관리할 것인지?
의견 부탁드립니다.

**Comment by aeroitems** [comment]
1번 형태가 좋을 것 같습니다.

추가 안건
1. 본문의 컬럼 수를 관리자가 지정할 수 있도록 한다. (1~6까지 직접 지정 - 메뉴 설정에서 선택)
2. 스크래퍼와 댓글의 위치 우선순위를 선택하도록 한다(모바일에서 스크래퍼가 아래로 내려가면 댓글을 먼저 보여줘야할 것인지 스크래퍼를 먼저 보여줘야할 것인지 사이트의 특성에 따라 다른 기호를 보일 것으로 생각됨) .
3. 스크래퍼가 모바일에서 나타나게할 것인지 사라지게 할 것인지 선택할 수 있도록 한다.(스크래퍼가 광고이거나 부연 정보일 경우 모바일에서 과감하게 삭제하는 것도 괜찮을 것이라는 생각. 다른 사이트들도 살리는 곳과 삭제하는 사이트가 둘다 존재함)
4. 위의 내용을 설정하는 곳은 메뉴 설정에서 하는게 좋을듯 합니다.
- 이러다 보니 **상단 메뉴 설정**이라는 이름을 바꿔야하지 않을까 싶네요. **'메뉴 및 레이아웃 설정'** 이라고 해야할까요? 이 부분에 대한 아이디어 주세요.

**Comment by baemoc** [comment]
스크래퍼와 댓글의 우선순위를 제외한 나머지 사항을 추가하였습니다.
