### ISSUE TITLE
상단 메뉴 영역을 줄이기 위한 조절

### ISSUE THREAD

**Issue by aeroitems** [netnamu/zinpack#112]
모바일에서 상단 영역의 공간 낭비가 심하다는 의견이 있습니다.
이것에 대한 조절이 필요할 듯 합니다.
- 모바일에서 메뉴 버튼의 위치를 검색의 링크 버튼 위치로 대치하고 링크 버튼을 삭제한다. 
  - 이것만으로  상단 낭비 공간의 상당 부분이 절약됨. 다만 링크 버튼이 없어지기는 하지만 아래에 링크 버튼이 존재하고 주소창을 통해 링크를 얻을수 있으므로 문제 없을 것으로 보임

**Comment by leihaht** [comment]
모바일에서 상단 공간을 줄이기위해서의 방안.
모바일에서 로고 이미지와 메뉴버튼을 같은 줄에 놓이게 한다.
로고 이미지는 왼쪽, 메뉴버튼은 오른쪽 -> 원래 Bootstrap에서 제공하는 구조입니다.
그에 따라 월간 금융조세 사이트의 로고 같은경우는 모바일에서 심히 보기 어려울정도로 작아지기에 로고 등록을 다시 해야될겁니다.

수정하기위해서는 css 및 html 코딩이 수정되야되네요.

**Comment by baemoc** [comment]
vendor.css에서 navbar-toggle 의 몇가지 style 을 주석으로 처리함.
logo-navbar 안에 들어가 있던 button을 searchbox 안으로 이동시킴.
sticky-anchor와 searchbox를 main-navbar 상단으로 이동시킴.

pc모드에서 메뉴가 옆으로 많이지게 되면, 검색이 위로 올라가게 됨.
mobile모드에서는 메뉴가 검색 밑으로 나오게 됨.
mobile모드에서 메뉴버튼을 클릭하면, 상단으로 스크롤 됨.

**Comment by leihaht** [comment]
흠... 제가 수정한 부분을 이메일로 보냈습니다.
배이사님이 수정한것을 적용하든 제가 수정한것을 적용하든 해주세요. ^.^/

**Comment by leihaht** [comment]
배이사님 의견으로 적용했다고 함. - by WKP
