### ISSUE TITLE
토픽박스 기능 개선

### ISSUE THREAD

**Issue by aeroitems** [netnamu/zinpack#115]
토픽 박스의 크기 지정 
현행 : 2칸 2줄 / 3칸2줄
개선 : 2칸1줄 / 3칸1줄 / 2칸2줄 / 3칸2줄 / 2칸3줄 / 3칸3줄 / 2칸4줄 / 3칸4줄

토픽 박스의 내용 지정
현행 : 제목+내용
개선 : 제목+내용 / 썸네일+제목+내용 / 제목만

**Comment by baemoc** [comment]
배너 크기도 3줄, 4줄이 추가 되었습니다.
스크래퍼에 모서리 둥글게, 테두리 두께, 테두리 색상이 추가되었고,
배경색은 hex값을 받아서 rgb로 변환하여 색상 그대로 투명해집니다.
투명해졌을 경우, 기존과 다르게 글자들은 투명해지지 않습니다.

**Comment by jejoongkim** [comment]
제목 + 내용 + 썸네일 에서 오류가 납니다.
썸네일이....비정상적으로 크게 표시 됩니다.

**Comment by baemoc** [comment]
썸네일의 경우 60x60 크기로 넣으셔야하고,
큰 이미지를 넣게 되면 60x60으로 썸네일이 만들어집니다.
