### ISSUE TITLE
페이지 상단 로고 좌우 정렬 선택 기능

### ISSUE THREAD

**Issue by aeroitems** [netnamu/zinpack#116]
페이지 상단 로고 정렬 위치가 가운데로 고정되어 있습니다. 
이것을 3가지중 한가지를 선택할 수 있게 개선되었으면 합니다.
1. 좌측 정렬
2. 가운데 정렬
3. 우측 정렬

**Comment by baemoc** [comment]
관리자페이지 > 디자인설정 > 기본설정 에 상단로고 정렬 이라는 옵션 추가하였습니다.

**Comment by jejoongkim** [comment]
테스트완료
