### ISSUE TITLE
스크레퍼로만 만드는 페이지 만들기

### ISSUE THREAD

**Issue by aeroitems** [netnamu/zinpack#117]
리스트 없이 스크레퍼로만 만드는 메인 페이지를 메인 이외에 다른 곳에서도 생성 할 수 있었으면 합니다.

현재는 메인 페이지만 이렇게 만들수 있으나 추가로 메인 페이지 스타일의 스크레퍼 페이지가 있으면 서브 메인의 역할로 사용하여 좀더 풍성한 뉴스 페이지 서비스를 만들 수 있을 것으로 기대합니다.

**Comment by baemoc** [comment]
메인 페이지는 그대로 존재하고,
메뉴 설정에서 스크래퍼 페이지를 추가할 수 있습니다.

**Comment by jejoongkim** [comment]
테스트해보았습니다.
