### ISSUE TITLE
다음한메일 회원가입메일 수신안됨

### ISSUE THREAD

**Issue by jejoongkim** [netnamu/zinpack#119]
지난번 네이버처럼 다음 한메일도 회원가입 메일이수신이안된답니다

**Comment by jejoongkim** [comment]
직접해보니 제꺼도 가입인증 메일이 도착하지 않습니다

**Comment by baemoc** [comment]
다음 고객센터에 메일차단 관련 문의해놓았습니다^^

**Comment by baemoc** [comment]
다음 메일차단 해제되었습니다^^

**Comment by jejoongkim** [comment]
월간항공은 스팸으로 들어가 있었고, 모터매거진은 안됩니다. 비건도 해봤는데 다음으로 회원가입 인증메일이 들어오질 않습니다. 12월13일 12시 시험

**Comment by jejoongkim** [comment]
비건......약 10분후 스팸메일로 들어왔습니다.

**Comment by jejoongkim** [comment]
테스트 결과 모터매거진 비건  다음메일에 스팸메일함으로 들어왔습니다.  15분후
