### ISSUE TITLE
신규 사이트 구축 안됨

### ISSUE THREAD

**Issue by jejoongkim** [netnamu/zinpack#120]
신규 사이트 구축시 에러 메시지 뜨고 돌아가 보면 구축은 되어 있으나

로긴해서 들어가면....해당카테고리가 없다는 무한 메시지가 반복 뜨면서 작동이 안됩니다.

현재 새로 만들어진 케이메디 사이트를 관리자 페이지를 통해서 들어가 보시면..어떤 증상인지 나옵니다.

www.info-way.co.kr/main/kmedi

**Comment by baemoc** [comment]
기본 디자인설정 DB가 생성이 안되는 오류가 있었습니다.
수정하였습니다^^

**Comment by jejoongkim** [comment]
테스트결과 사이트는 생성되었습니다. 그러나 디자인 템플릿 적용이 세이브해도 변경되지 않습니다.

**Comment by baemoc** [comment]
수정 완료하였습니다^^
