### ISSUE TITLE
토픽 제목 앞에 블릿 + 더보기 기능 삼각형 사용자 지정기능

### ISSUE THREAD

**Issue by baemoc** [netnamu/zinpack#121]
토픽 제목의 앞부분에 블릿 기호를 넣을 수 있는 기능 필요
토픽의 더보기 삼각형을 사용자가 지정하여 변경 할 수 있는 기능 필요

**Comment by baemoc** [comment]
개요 모양/더보기 모양 추가하였습니다.
한글로 4글자까지 입력가능합니다.
더보기 모양은 필수입력이고,
토픽생성시 ▶ 세모가 기본값으로 설정되어 있습니다.

**Comment by jejoongkim** [comment]
테스트 페이지 테스트 해보았습니다. 그런데...화살표도 넣어보고..별표..네모  세모 넣어봤습니다. 폰트가 좀 더 작으면 어떨까요? 더봐라 라고 넣어봤는데....폰트 크기가 앞의 제목과 똑같으니까 좀 이상한 듯 했습니다.

**Comment by baemoc** [comment]
글자 크기를 조금 줄였습니다.
