### ISSUE TITLE
위챗 큐큐 공유 단추 추가 

### ISSUE THREAD

**Issue by jejoongkim** [netnamu/zinpack#122]
케이메디 중국 서비스를 위한 중국 SNS 추가 입니다

**Comment by baemoc** [comment]
위챗은 ios와 안드로이드 공유하기만 있는 것 같구요.
큐큐는 중국어라 어디로 들어가봐야할지 모르겠습니다.

javascript나 php로 공유 연동이 되어야 저희 사이트에 적용 가능합니다.

**Comment by aeroitems** [comment]
http://world.chinadaily.com.cn/2014-12/17/content_19110014.htm
여기에 보면 하단에 공유하기 중국판이 있네요...
이걸 다 지원해야한다는 걸까요??? ㅠ.ㅠ

**Comment by jejoongkim** [comment]
http://wiki.connect.qq.com/sdk%E4%B8%8B%E8%BD%BD
http://wiki.open.qq.com/wiki/API%E5%88%97%E8%A1%A8  큐큐 api 관련 페이지 인 듯 합니다...
어렵게 찾았으나..관련 있는지.....번역기 돌리면 대충 알아는 봅니다.

**Comment by baemoc** [comment]
위의 API는 로그인과 관련한 것입니다.
차후에 소셜댓글에 사용할 수 있는 내용입니다.

제가 찾아본 결과
위챗은 공유가 없고, 큐큐는 QZone이라는 URL공유가 가능하네요.
추가로 중국에서 쓰는 것들 찾아서 적용하였습니다.
테스트 부탁드리겠습니다.

Delicious
https://delicious.com/

Tumblr
https://www.tumblr.com/

Digg
http://digg.com/

StumbleUpon
http://www.stumbleupon.com/

Reddit
http://www.reddit.com/

新浪微博(Sina Weibo)
http://overseas.weibo.com/

QQ 空间(QZone)
http://qzone.qq.com/

人人网(Renren)
http://www.renren.com/

腾讯微博(Tencent Weibo)
http://t.qq.com/

**Comment by jejoongkim** [comment]
케이메디쪽 편집장과 공유하여 테스트 해보도록 하겠습니다.

**Comment by jejoongkim** [comment]
테스트 결과 이상없이 공유 된다고 합니다.
