### ISSUE TITLE
쇼핑몰 주문시 메일 전송 기능

### ISSUE THREAD

**Issue by aeroitems** [netnamu/zinpack#124]
쇼핑몰에 주문이 들어오면 사이트 관리자와 상품 관리자에게 메일이 전송되는 기능이 필요합니다.

**Comment by baemoc** [comment]
일단 메일로 보내지는 폼을 짜야되지 않을까요?

**Comment by aeroitems** [comment]
폼메이커를 만들어야 하는 건가요?
이런건 사실 특수한 경우라 별도의 폼 생성 비용을 받아 만들어 주도록 하는것은 어떨까요?

**Comment by baemoc** [comment]
보내고자 하는 메일의 자세한 내용들이 필요합니다.
1 보내는이 메일
2 제목
3 내용
데이타 종류(상품이름, 결제자, 가격 등)
노출 형식(테이블, 텍스트 등)

**Comment by jejoongkim** [comment]
텍스트 노출, 
제목 : (알림) @@@님이 쇼핑몰에서 주문한 내역입니다.
내용 : 주문한 상품 목록, 가격, 주소?  
보내는이 메일은 : 인포웨이글로벌 관리자

**Comment by baemoc** [comment]
제목: [사이트명] 쇼핑몰에 주문이 접수되었습니다.
내용: 주문번호(주문조회링크), 구매자명

가상계좌는 입금이 완료되면, 메일로 전송.
사이트 관리자와 각 판매자에게 메일이 전송.
