### ISSUE TITLE
페이지뷰, 추천, 댓글수 삭제 옵션

### ISSUE THREAD

**Issue by jejoongkim** [netnamu/zinpack#126]
퍼블릭아트사와 모터매거진사에서는 게시물 조회수를 보여주지 않았스면 좋겠다는 의견이 있는데
1. 업체가 디자인 설정에서 옵션으로 설저앟게 한다.
2. 사이트 구축 과정에서 회원노출설정, 회원가입 설정 이 있는 곳에서 처음에 선택하게 한다.

두가지를 생각해 봤는데 개인적으로는 2번이 어떨까 합니다.

**Comment by baemoc** [comment]
[ 관리자 > 디자인설정 > 게시판 기본 설정 ] 추가.
게시판 별로 설정가능.
목록/검색목록/상세뷰/토픽 에도 똑같이 적용됩니다.

1 기본정보 노출
날짜/글쓴이/조회수/댓글수/추천수

2 부가 기능 노출
포인트선물하기/댓글/추천

3 SNS공유 노출
URL복사/페이스북/트위터/Google+/Pinterest/Linkedin/Delicious/Tumblr/Digg/StumbleUpon/Reddit/新浪微博/QQ 空间/人人网/腾讯微博/카카오톡/라인
