### ISSUE TITLE
폰사진 업로드시 가로 모드 세로 모드 자동 인식 필요

### ISSUE THREAD

**Issue by aeroitems** [netnamu/zinpack#128]
폰 사진은 세로 사진이 많은데 사진 업로드시 모두 가로로만 인식해서 올라가고 있습니다.
가로와 세로를 자동으로 인식하여 업로드 되었으면 합니다.
원래 되는데 폰 버그 일까요?
소이바이오틱스 에서 업로드 하니 그렇게 나오네요... ^_^;

**Comment by baemoc** [comment]
간편모드/웹에디터 등록시
사진의 Orientation 값을 가져와 자동으로 회전을 시키고
가로 1100px에 맞춰 다시 리사이징 하여 저장합니다.
