### ISSUE TITLE
페이스북으로 공유시  nbsp등 코딩언어 노출 & 사진이 안나옴

### ISSUE THREAD

**Issue by jejoongkim** [netnamu/zinpack#129]
페이스북 공유시 코딩언어들이 과도하게 나오는 듯 합니다.
그리고 사진이 안 보이는 경우가 많습니다.

**Comment by baemoc** [comment]
첫째로 태그를 전부 제거하고,
html엔티티 중 띄어쓰기, 따옴표, 작은따옴표, 앰퍼샌드 를
따로 특수기호로 바꾸어 전송하도록 변경하였습니다.
위의 것을 제외한 특수문자는 모두 제거됩니다.

사진의 경우는 안보일수도 있습니다.

**Comment by jejoongkim** [comment]
링크 실험을 10여번 해보았습니다. 사진, 제목, 본문 처음 내용 모두 안나오고 www.ifwy.net 주소만 밑에 나옵니다.

**Comment by jejoongkim** [comment]
![2015-01-09 19 34 53](https://cloud.githubusercontent.com/assets/8475290/5678513/a037a988-9836-11e4-979b-f2be91d8f75e.PNG)

**Comment by baemoc** [comment]
페이스북이나, 구글플러스 같은 경우에는
meta 태그에 지정해놓은 제목,내용,이미지 값을 가져다가 쓰기때문에

[ 사이트에서 데이타 전달 -> 페이스북 노출 ]이 아닌
[ 사이트에서 url전달 -> 페이스북에서 사이트 접근 -> 페이스북 노출 ] 로 이루어집니다.

페이스북에서 접근을 시도하는 순간 비회원이기 때문에
1 사이트가 회원공개
2 분류별로 비회원 윗등급에만 공개
3 그룹이 비공개
위의 경우들에는 제목,내용,이미지 모두 노출이 안됩니다.
