### ISSUE TITLE
해당 카테고리에 접근 권한이 없습니다. 메시지 수정이 필요

### ISSUE THREAD

**Issue by jejoongkim** [netnamu/zinpack#130]
로긴을 해 놓은 상태에서 해당 권한이 없습니다. 라고 나오면 이해가 가는데
비회원의 경우 해당권한이 없습니다 라고 나오면 그냥 아..여기는 못 들어가는 곳인가 보다..라고 생각하고 아예 보지도 않는 경우가 생깁니다.
1. 모터 바이크 매거진 (화보 카테고리를 로긴한 회원에게만 보여주고자 기획중입니다)
2. 비회원이 접근하면 '해당카테고리에 접근권한이 없습니다" 보다는 "로그인 후 이용해 주세요" 라는 메시지가 뜨고 바로 로그인 페이지로 이동하는 UX가 필요 할 듯 합니다.
3. 기획의 의도가 달라서 그렇다면  회원이 접근하는 경우에는 권한이 없습니다...라고 보여지고  비회원이 접근하면 "로그인 후 이용해 주십시오" 라고 메시지가 다르게 보여야 할 듯 합니다.

**Comment by baemoc** [comment]
분류별로 회원등급이 있는 경우.
비회원 : 로그인 요청 > 로그인 > 다시 페이지로 복귀(등급이 맞다면!)
회원 : 등급이 낮다면 접근권한 없음 알림

테스트 부탁드리겠습니다.

**Comment by jejoongkim** [comment]
로그인하지 않은 상태에서는 로그인하라는 메시지가 뜨고
로그인 한 상태에서 해당 카테고리 권한이 없을 경우 권한이 없다는 메시지가 뜨는 걸로 확인 테스트 완료
