### ISSUE TITLE
테스트 페이지에서 간편모드로 글 작성시 오류

### ISSUE THREAD

**Issue by jejoongkim** [netnamu/zinpack#132]
![2015-01-26 20 36 08](https://cloud.githubusercontent.com/assets/8475290/5899173/0f52f4aa-a59b-11e4-87a9-49ff3040c106.PNG)

간편 모드로 글 올리고 나니 에러 메시지 뜹니다

**Comment by baemoc** [comment]
간편모드로 수정하신걸로 보이는데요.
확인해보니 잘됩니다. 이미지파일이 이상한 경우 같습니다.
