### ISSUE TITLE
메인슬라이드 추가시 새로운 메인슬라이드가 맨 위에 오도록?

### ISSUE THREAD

**Issue by jejoongkim** [netnamu/zinpack#134]
기존 슬라이드 1 이 있고 거기에 2를 추가 할 경우

2가 맨 앞에 보여져야 합니다. + 를 눌르면 밑으로 들어가서 슬라이드가 1 2 의 순서로 화면에서 보여지는데
- 그 순서를 지정하게 하는 방법이 있을까요? 전에...메인슬라이드 순서를 지정하는게 있었던듯?

**Comment by baemoc** [comment]
슬라이드와 배너의 경우, 직접입력 선택을 하면 노출순서를 입력할 수 있습니다.
