### ISSUE TITLE
메뉴의 위치 변경

### ISSUE THREAD

**Issue by baemoc** [netnamu/zinpack#137]
로고 하단 or 로고 우측

**Comment by jejoongkim** [comment]
잘 움직입니다.

**Comment by baemoc** [comment]
메뉴가 상단에 붙을 경우, 로고 이미지 크기에 유의해 주시기 바랍니다.
검색부분도 테스트 해주시기 바랍니다.

모바일에서 하위 메뉴를 열고 아래로 스크롤시,
하위메뉴까지 밑으로 따라오기 때문에 메뉴가 많아지게 되면
하위메뉴를 선택할 수가 없어질 것으로 보입니다. 확인부탁드립니다.

**Comment by jejoongkim** [comment]
테스트 결과...모바일에서 메뉴를 눌러서 메뉴가 밑으로 쭉 디스플레이 된 상태에서..손가락으로 화면을 스크롤해서 올렸더니..

어느 순간....갑자기 위로 확 자동으로 올라가는 현상이 발생하고 있습니다. 

메뉴가 많아도 손가락으로 스크롤해서 볼 수는 있는 듯 합니다.

**Comment by jejoongkim** [comment]
메뉴는 양이 많아도 스크롤을 하면 밑에꺼도 볼 수 있는 듯 합니다.

메뉴를 열어 놓은 상태에서는 처음에는 메뉴도 같이 스크롤 되어 보는데 지장이 없으나 화면이 한번...움찔 하고..다시 화면이 셋팅 된 다음에는 메뉴를 스크롤 할 수는 없습니다. 이 부분은 왜 그런지 알 것 같습니다. 사용자 교육을 통해 해결해야 할 듯 합니다.
