### ISSUE TITLE
네비게이션바 노출 선택

### ISSUE THREAD

**Issue by baemoc** [netnamu/zinpack#138]
노출 or 숨김
숨김에  따른 버튼 위치 변경
노출 : 네비게이션바 우측
숨김 : 하단 로그인 버튼 우측

**Comment by jejoongkim** [comment]
숨김을 선택해도 네비게이션바(브래드크롬)이 없어지지 않습니다.

**Comment by baemoc** [comment]
breadcrumb 을 제거해보니,
현재 리스트가 무슨 리스트인지도 알수가 없고,
개인정보취급방침,이용약관,장바구니,포인트내역,구매내역,포인트충전,회원가입,회원정보수정,비밀번호찾기,검색 에서 무슨페이지인지 알수가 없습니다.

현재 랜딩페이지와 스크래퍼 페이지에만 breadcrumb을 제거가 가능하도록 해놨습니다.

**Comment by jejoongkim** [comment]
테세트완료
