### ISSUE TITLE
메뉴를 로고 오른쪽으로 했을 때 해당 부분 배경색상 지정

### ISSUE THREAD

**Issue by jejoongkim** [netnamu/zinpack#139]
로고와 메뉴를 화면 맨 위 한 줄로  위치하게 할 경우 해당 부분의 배경색상을 따로 지정할 수 있으면 합니다.

**Comment by baemoc** [comment]
1 메뉴 > 로고 하단
메뉴부분 배경 : 없음.
아래로 끌어내렸을 경우 : 배경 > 배경색상

2 메뉴 > 로고 우측
메뉴부분 배경 : 상단메뉴 > 배경색상
아래로 끌어내렸을 경우 : 상단메뉴 > 배경색상

**Comment by jejoongkim** [comment]
테스트 완료
