### ISSUE TITLE
도로명 주소 법령에 따라 옛 주소로 주소 정보를 받으면 안된다네요

### ISSUE THREAD

**Issue by jejoongkim** [netnamu/zinpack#141]
월항에서 전화가 왔습니다.

기존 주소로 접수 받으면 안되고 도로 주소로 받으라고 하는 전화가 왔답니다.

법령이..지금까지는 시범기간이고 이제는 정식으로 도로명 주소만 쓰도록 한다네요

도로명 주소 시스템이 갖춰 지던지...

아니면..그냥 직접 입력하도록 해야 할 것 같습니다.

**Comment by baemoc** [comment]
회원가입/회원정보수정/쇼핑몰배송/판매자신청/판매자정보수정
우편번호를 직접 입력하도록 변경하였습니다.
