### ISSUE TITLE
커피앤티 참가 신청서들 독립페이지로 코딩 요청

### ISSUE THREAD

**Issue by jejoongkim** [netnamu/zinpack#143]
커피앤티와 계약 진행시 협조해주기로 했던 참가 신청서 양식
1. 선택 항목들을 풀다운 메뉴 형식으로 해서 선택할 수 있도록
2. 주소, 전화번호, 사업자 등록 번호 등을 직접 입력할 수 있도록
3. 입력된 내용을 이메일 보내기 단추를 누르면 정해진 메일로 보내 지도록

기본 양식은 거의 비슷합니다. 위 아래 안내 글 들은 제가 직접 작업이 가능하나
여러 가지 선택사항들을 선택하고 내용을 넣도록 하는 부분은

ck 에디터로 주말에 시도해보았으나 방법을 찾지 못하여 코딩을 하는 수 밖에 없을 듯 합니다.

**Comment by baemoc** [comment]
김이사님 메일로 신청서페이지 작성하는 법 보내드리겠습니다.
