### ISSUE TITLE
무료배송입니다

### ISSUE THREAD

**Issue by jejoongkim** [netnamu/zinpack#144]
판매자가 일정 가격 이상은 무료 배송을 할 수 있도록 설정했으면 합니다.

**Comment by baemoc** [comment]
판매자로 접속하여.
쇼핑몰 > 배송코드관리 로 들어가시면,
아래의 옵션 중 하나로 선택 가능합니다.

1.배송비무료 (몇원 이상 무료배송)
배송코드가 같으면 설정해놓은 가격 이상일 경우 배송비가 0원이 됨.

2.최대수량 (몇개 이하 묶음배송)
배송코드가 같으면 설정해놓은 개수까지만 배송비 1회 적용.
설정 개수가 초과될 시, 배송비 1회 추가 적용되는 방식.
