### ISSUE TITLE
댓글 알림 

### ISSUE THREAD

**Issue by jejoongkim** [netnamu/zinpack#145]
댓글이 달렸을때 해당 게시물과 같이 메일로 알려주는 것이 필요할 듯 합니다. 

메일 발송자 : 인포웨이글로벌
메일 내용 : 게시물 제목 (해당 게시물로 바로 가기)
                  댓글 내용

**Comment by baemoc** [comment]
댓글이 달리면 메일 전송.
보내는 이는 "사이트명(사이트관리자 메일주소)"
받는 이는 "글 작성자"

**Comment by jejoongkim** [comment]
댓글 이 달린 후 해당 사이트 관리자 이메일로 알림이 오는 것을 테스트 완료 했습니다.
