### ISSUE TITLE
소셜공유 버튼 선택 - 기본 or 테마

### ISSUE THREAD

**Issue by baemoc** [netnamu/zinpack#147]
관리자 - 디자인 설정 - 기본 설정 에 [소셜공유 버튼] 추가
1. 기본(고유색상) 선택 시, 각 회사별 아이콘 이미지 노출
2. 테마 선택 시, 테마디자인에서 지정한 버튼 색상으로 노출

**Comment by jejoongkim** [comment]
변경 해 보았습니다. 설정에 따라 바뀌는 지 여부 테스트 완료
