### ISSUE TITLE
비밀 게시글 및 비밀 댓글

### ISSUE THREAD

**Issue by baemoc** [netnamu/zinpack#149]
비밀 게시글은 본인 및 사이트관리자만 확인.
비밀 댓글은 본인 및 글 게시자와 사이트관리자만 확인.

**Comment by baemoc** [comment]
비밀 게시글
1.글쓰기에서 옵션으로 추가함.
2.기존의 좌우여백을 체크박스로 변경.
3.목록, 토픽, 검색목록에 "비밀글입니다." 라고 표시.
4.글 상세보기에서 제목 오른쪽에 자물쇠 표시.
5.관리자페이지 뉴스 상세보기에서 "좌우여백(O)/비밀글(O)" 표시.
6.글쓴이,사이트관리자,그룹관리자 만 볼수 있음.
7.접근권한이 없으면 "비밀글입니다."라고 경고.

비밀 댓글
1.댓글쓰기에 비밀글 체크박스 추가.
2.글쓴이,댓글작성자,상위댓글작성자,사이트관리자,그룹관리자 만 볼수 있음.

**Comment by jejoongkim** [comment]
비밀글을 접근할 수 없슴을 확인했습니다.  비밀글 작성을 확인했습니다.
