### ISSUE TITLE
스크래퍼를 세로 4칸에서 8칸으로 변경

### ISSUE THREAD

**Issue by baemoc** [netnamu/zinpack#159]
1. 4칸으로 되어있던 것을 1칸의 절반 크기로 나눠서 8칸으로 만듦.
2. PC와 아이패드 크기에서는 가로의 비율로 세로 크기가 줄어듦.
3. 모바일에서는 기존과 동일한 크기로 유지.
4. 직접 등록한 배너는 칸 수와 관계없이 가로x세로 가 항상 비율 유지.
   (pc버전의 크기에 맞춰서 등록해야 함.)

**Comment by baemoc** [comment]
화면 너비에 따른 세로 크기의 변화에 따라
토픽의 줄 수를 조정하도록 변경함.

**Comment by jejoongkim** [comment]
배너의 경우 이미지 크기에 따라서 세로 크기가 마음대로 변합니다. 똑같이 3X3 배너로 만들어도 이미지 크기가 세로로 길거나 하면 저절로 세로 크기가 늘어나 버립니다. 
가로 길이는 고정됩니다. 테스트 사이트 맨 밑줄 참고 바랍니다. 모두 똑같이 3X3 인데 크기가 틀립니다

1X1 의 경우에도 이미지가 배너보다 작으면 저절로 배너 크기 자체가 (세로) 줄어드는 듯 합니다.

**Comment by jejoongkim** [comment]
아.....해결되었습니다. 처움부터 만들때.. 미리 써 놓은 픽셀 수에 맞추어서 배너를 제작하면 되는 거군요

**Comment by baemoc** [comment]
직접 등록의 경우는. 이미지 자체의 비율을 가지고 갑니다.
