### ISSUE TITLE
RSS feedback 기능 추가

### ISSUE THREAD

**Issue by aeroitems** [netnamu/zinpack#16]
RSS  기능을 추가하여 사용자들이 구독을 할 수 있도록 기능 추가

**Comment by baemoc** [comment]
rss feed
사이트와 그룹 다 필요한가요?
뉴스/쇼핑몰/이북/컨텐츠 각각 다 필요한가요? 뉴스만 필요한가요?
몇개가 노출되야 하나요? 평균 10~20정도인 것 같습니다.
- rss url 예정
  www.info-way.co.kr/rss/?site=[사이트코드]&group=[그룹코드]&type=[뉴스]&limit=[숫자]

**Comment by baemoc** [comment]
RSS url을 복사할 버튼 or RSS xml페이지로 이동할 버튼 필요합니다.
RSS를 설명해줄 페이지가 필요한지요?

**Comment by baemoc** [comment]
뉴스만 RSS 사용
(사이트 or 그룹별) + 카테고리별  피드 받을 수 있음
노출갯수는 최대 100개로 사용자가 임의로 변경가능
RSS버튼은 뉴스의 글쓰기 버튼 옆에 위치함
카테고리 내에서 RSS버튼 클릭시 해당 카테고리만 feed될 url 노출

-rss url 예시
www.info-way.co.kr/rss/?ep=[사이트코드]&gp=[그룹코드]&cg=[카테고리코드]&limit=[노출갯수]

**Comment by aeroitems** [comment]
mac 에서  fresh feed pro로 테스트 - 잘됨
![2014-08-22 4 56 22](https://cloud.githubusercontent.com/assets/8153667/4008090/e2b09816-29d1-11e4-9c39-504e91905dcd.png)

**Comment by aeroitems** [comment]
권한 없는 게시판의 게시물도 잘 스크랩됨.
아이폰과 맥에서 테스트 통과
PC에서 브라우저를 통해 지정하고자 할 경우 브라우져의 RSS 기능을 쓰기엔 어떤지 확인이 필요.
다른 리더에서는 올바르게 작동함.

**Comment by aeroitems** [comment]
브라우저의 주소창에 입력후 피드 북마크를 하면 해결됨.
