### ISSUE TITLE
pdf 스타일 에서 좌수 우수 보기 문제

### ISSUE THREAD

**Issue by aeroitems** [netnamu/zinpack#163]
책이 오른쪽으로 넘기는 책과 왼쪽으로 넘기는 책이 있습니다.
보통 도서는 오른쪽으로 넘기는 책(우수)인데
ixDesign 같은 경우는 왼쪽으로 넘기는 책(좌수) 입니다.

도서등록시 
오른쪽 넘김은 1페이지 부터 시작하고
왼쪽 넘김은 맨 마지막 페이지 부터 시작 하도록 
시작 페이지를 설정 할 수 있는 기능을 추가 바랍니다.

이 기능은 pdf 스타일로 지정후 편집 에서 설정하는것이 좋겠습니다.
티폴트는 오른쪽 넘김 
다른 항목은 왼쪽 넘김
둘중 하나를 선택하도록 하고 아무것도 안지정하면 디폴트인 오른쪽 넘김이 자동 지정되도록

**Comment by baemoc** [comment]
PDF 등록시, 읽는 방향 추가.

**Comment by aeroitems** [comment]
이미 등록된 PDF 파일의 eBook의 방향을 수정하여 변경할 수 없음.
파일을 다시 등록해야함.
파일을 다시 등록하지 않고 현재 있는 파일의 수정사항만을 받아 들일 수 있도록 개선 요망

**Comment by baemoc** [comment]
수정 완료.
