### ISSUE TITLE
복제방지 기능의 온/오프 

### ISSUE THREAD

**Issue by aeroitems** [netnamu/zinpack#165]
1. 사이트 정책중 복제 방지 기능(마우스 오른쪽 클릭 방지)을 온/오프로 설정하거나
2. 가능하다면 게시판 별로 복제 방지를 온/오프 할 수 있도록 했으면 좋겠음.

1.의 경우라면 기본설정에서 설정하도록 하고 / 
2의 경우라면 분류관리 에서 설정할 수 있도록 기능 추가 요망
가능하다면 2번 희망 어렵다면 1번이라도...

**Comment by baemoc** [comment]
복제 방지 기능은 없어도 될 것 같습니다.
이 기능을 쓰면 자바스크립트 오류가 나기도 하고,
어차피 소스보기 하면 다 보이는 내용입니다.

**Comment by aeroitems** [comment]
그렇다면 기본으로는 복제 방지 기능이 없는 것으로 하고
옵션으로 마우스 오른쪽 버튼 방지를 넣는 것은 어떨까요? 오류 경고는 하고...(브라우저에 따라 자바스크립트 오류가 발생할 수 있습니다.)

이거 해달라고 한 업체들이 있으니 안할 수는 없을듯 해서 그럽니다.
정 필요가 없다라고 생각한다면 빼는 것도... ㅠ.ㅠ 고려해 봅시다.

**Comment by baemoc** [comment]
SUPER 관리자
[정보관리 / 사이트관리]
복제 방지 ON/OFF 추가.

마우스 드래그, 마우스 오른쪽, 팝업메뉴, ctrl + c 키 방지
(크로스 브라우징 처리)
