### ISSUE TITLE
여러개의 이북을 구입했을때 목록 오류

### ISSUE THREAD

**Issue by aeroitems** [netnamu/zinpack#166]
여러개의 이북을 구입했을때 목록이 겹쳐 보이게 됨.
구입 목록에 나타나는 이묵들이 겹쳐 나타남.
![error_20150728](https://cloud.githubusercontent.com/assets/8153667/8926911/8d182a5c-354e-11e5-8b5b-f6bd26f8cc28.jpg)

**Comment by baemoc** [comment]
테스트 사이트에 오류 수정
