### ISSUE TITLE
정산에 필요한 추가 사항들

### ISSUE THREAD

**Issue by aeroitems** [netnamu/zinpack#172]
1. 결재 내역에서 필요한 필드들
2. 판매자(이름/아이디) : 누가 판매했는지 알아야될 필요가 있음(정산 분배시 누가 올린건지 알아야 돈을 보내줄수 있음.
3. 과세/면세 여부 : 과세인지 면세 인지에 따라 세금 계산과 매출액이 달라지므로 이것을 반드시 알아야함
4. 판매 그룹 : 어느 그룹에서 매출이 일어 났는지 확인이 필요함
5. 배송진행 상태 : 현재 배송이 완료된 것인지 접수중인지 확인이 필요함.

**Comment by baemoc** [comment]
슈퍼관리자인지, 사이트관리자인지,
그리고 어떤 메뉴의 어디에서 출력해야하는지 궁금합니다.

**Comment by aeroitems** [comment]
super 관리자
결제시스템 / LGU+ 결제내역
결제시스템 / LGU+ 취소내역
에서 아래의 내역이 시트로 나오도록 개선 요망
기존의 시트에 뒤에 아래 필드 추가.

|   판매자ID|    판매자이름|    부가세|  판매그룹ID| 판매그룹이름| 배송상태

아래는 전체 필드 목록
번호| 업체명|  사이트코드|    회원코드|   주문번호|   결제응답|   LG유플러스 거래번호|    LG유플러스 발급 아이디|    결제금액    입금액|  결제수단|   구매자명|   구매내역|   결제기관명|    신용카드번호| 결제휴대폰번호|  등록일|  판매자ID|    판매자이름|    부가세|  판매그룹ID| 판매그룹이름| 배송상태

**Comment by baemoc** [comment]
결제내역은 PG사와 통신한 내용만 담고 있습니다.
한 결제 안에 여러 상품과 판매자가 존재하며,
그 안에서 옵션별로 배송유무가 확인되기 때문에 결제내역에서 확인하는 것은 무리가 있습니다.
쇼핑몰 주문내역에 넣는게 어떨까요?

**Comment by baemoc** [comment]
SUPER관리자 / 매출관리 / 쇼핑몰 주문내역
상태/기간/검색 3가지로 검색한 내용을 엑셀로 뽑을 수 있도록 변경하였습니다.

번호 | 사이트 | 사이트코드 | 그룹 | 그룹코드 | 판매자 | 판매자코드 | 회원 | 회원코드 | 주문일자 | 주문번호 | 주문자 | 연락처 | 상품명 | 옵션 | 금액 | 수량 | 주문금액 | 배송비 | 부가세 | 상태 | 결제방식 | 결제일자 | 결제응답 | LG유플러스 거래번호 | LG유플러스 아이디 | 결제금액 | 입금액 | 결제수단 | 구매자명 | 구매내역 | 결제기관명 | 신용카드번호 | 휴대폰번호
