### ISSUE TITLE
이북 샘플 보기 기능

### ISSUE THREAD

**Issue by aeroitems** [netnamu/zinpack#174]
PDF 이북의 경우에만 해당 하며
본편 pdf 등록 이외에 샘플 pdf 를 등록 할 수 있도록 하여
구입 없이 샘플을 볼 수 있는 기능이 필요.

샘플보기 버튼을 이북에 넣어주세요. 
샘플은 회원 등급에 따라 열람이 가능하도록 지정 하는 기능이 필요.
비회원에서 부터 0~9 등급 까지 지정 - 입력/수정시 조절 가능하도록

**Comment by baemoc** [comment]
사이트 관리자
[이북몰 / 전체 이북 조회]
[이북몰 / 이북 등록 승인]
미리보기 옆에 샘플 미리보기 버튼 추가.

[이북몰 / 분류관리]
샘플보기 권한 추가.

회원
[이북물 / 이북관리]
미리보기 옆에 샘플 미리보기 버튼 추가.
편집으로 들어가면 하단에 샘플 등록하는 곳으로 가는 버튼이 있음.
샘플로 들어가게 되면 원본으로 돌아오는 버튼이 있음.

샘플보기 버튼
사이트관리자, 이북등록한 판매자, 설정한 등급이상인 자에게만 버튼 노출.
