### ISSUE TITLE
사각형 간격 조절 기능

### ISSUE THREAD

**Issue by aeroitems** [netnamu/zinpack#177]
각 타일 간의 간격을 조절 하는 기능 추가

관리>테마디자인>설정
배경에 "타일 간격" 항목 추가
기본값

타일간격 [            ] px (0 ~ 99)

**Comment by baemoc** [comment]
전체의 박스 간격 설정과 스크래퍼는 별도의 박스 간격 조절 가능.
스크래퍼를 새로 생성시, 전체박스간격을 기본값으로 넣어둠.
테마를 선택해서 변경시 기본값(5px)로 변경 됨.

[디자인 설정 / 테마디자인 설정]
박스 공통에 간격 추가!

[스크래퍼]
박스간격 추가!
