### ISSUE TITLE
뉴스에 공지사항 제거 / 인기뉴스로 대체

### ISSUE THREAD

**Issue by aeroitems** [netnamu/zinpack#19]
중단 배너와 토픽의 구조를 단순화

**Comment by aeroitems** [comment]
뉴스 메인을 랜딩메인처럼 토픽과 배너를 추가하거나 수정할 수 있도록 하는 기능을 넣는건 어떨런지요?
메인에서는 "Hot Issue" 라고 썼는데 뉴스에 와서는 무조건 "인기" 라고 표현되니 아쉬움이 있네요.

**Comment by baemoc** [comment]
토픽 형태를 뉴스만 적용할 것인지요?

**Comment by aeroitems** [comment]
토픽 형태는 뉴스와 이북, 콘텐츠, 쇼핑몰 등 모두에 적용해야할 기능으로 보입니다.
각 섹션도 메인처럼 토픽과 배너를 설정하도록 하였으면 좋겠습니다.
메인의 토픽설정, 배너 설정과 동일한 기능이었으면 좋겠고, 다만 위치를 리스트의 상단에 나타나게 할 것인지 하단에 나타나게 할것인지 설정하는 기능이 추가 되었으면 좋겠습니다.
그래서 상단과 하단에 동시에 여러개가 나타나게 할 수 있으면 합니다.
배너 이미지는 외부 링크를 입력 하는 것도 가능하게 되었으면 좋겠습니다.
