### ISSUE TITLE
핀터레스트 스타일의 목록 추가

### ISSUE THREAD

**Issue by aeroitems** [netnamu/zinpack#20]
메인 뉴스의 리스트 방식을 두가지 중 하나로 선택 할 수 있는 기능 추가

**Comment by baemoc** [comment]
뉴스만 적용하나요?

**Comment by aeroitems** [comment]
네 이 기능은 뉴스에만 적용합니다.

**Comment by baemoc** [comment]
뉴스,쇼핑,이북,컨텐츠 모두
2단/4단/6단 형태로 변경 가능하도록 할 예정임.

**Comment by jejoongkim** [comment]
Great!

**Comment by baemoc** [comment]
4단 형식으로 제가 바꿀수 있을 줄 알았는데, 4단 디자인이 필요합니다.

**Comment by aeroitems** [comment]
4단을 어떻게 하면 할 수 있을지 최 이사님께서 검토해봐 주시기 바랍니다.
CSS를 수정해야하는건지 기존에 적용할 수 있는 방법이 있는지... 검토 요청합니다.

**Comment by leihaht** [comment]
메뉴를 4단이상 되면 보기 너무 안좋을것같은데,
그럴바에는 이런 디자인이 아니라 다른 디자인이 필요할것 같습니다.

**Comment by leihaht** [comment]
아.. 제가 잘못 이해했네요. 메뉴가 아니라,
뉴스 페이지의 리스트 방식을 4컬럼이나 6컬럼으로 하시는걸 말씀하시는거군요.
그건 html을 수정해야됩니다. css에는 이미 그 기능이 내제되있어요.

**Comment by aeroitems** [comment]
최이사님 html에서 어떻게 수정하면 되나요?? 6컬럼은 해봤는데 4컬럼은 어떻게 하는지 몰라서요. 알려주세요.

**Comment by leihaht** [comment]
그러고보니 현재 레이아웃은 6컬럼 시스템이라서 4컬럼으로 만들지는 못하는군요.
그냥 bootstrap의 12컬럼 시스템으로 레이아웃을 만드는게 좋았을거네요.
처음 만들때는 이런것까지 고려하지않은거라서요.
현재 시스템에서 4컬럼을 만드려면 레이아웃을 통채로 바꿔야됩니다.
그렇게 되면 지금 현재 쓰는것도 전부 바꿔야되요.

**Comment by aeroitems** [comment]
그럼 3컬럼 시스템을 만드는 것은 지금 가능하겠군요?
2 / 3 / 6 이렇게 만들수 있는 건가요?

**Comment by leihaht** [comment]
6컬럼(열) 시스템이라서 그걸 나눠서 만들수있는건 다 할수있죠.
1 / 2 / 3 / 6 컬럼(열) 이런식이죠.

**Comment by baemoc** [comment]
관리자 페이지 - 디자인 기본설정 에서
뉴스/쇼핑몰/컨텐츠몰/이북몰 각각
2단 / 3단(정렬) / 3단(쌓기) / 6단(정렬) / 6단(쌓기)
선택 할수 있습니다.
쌓기의 경우 핀터레스트와 같은 레이아웃입니다.

**Comment by aeroitems** [comment]
네 고생하셨습니다. 테스트 하겠습니다.

**Comment by aeroitems** [comment]
테스트 완료
컬럼 변경은 이상없이 잘됨
너무 산만한 면도 있음. 
향후 디자인에 수정이 필요할 듯함.

**Comment by baemoc** [comment]
3단과 6단 고정형 스타일 추가.

**Comment by aeroitems** [comment]
3단 고정
6단 고정 
테스트 완료 롹인 완료

**Comment by aeroitems** [comment]
이미지 위주로 리스트를 꾸밀때 사용하는 고정형 리스트는 임시로 오픈하고
사용 추이를 보고 요구 사항에 따라 디자인 수정을 하던지 해야할 것 같습니다.
