### ISSUE TITLE
게시판에 파일 첨부 기능 추가

### ISSUE THREAD

**Issue by aeroitems** [netnamu/zinpack#23]
게시판에 파일 첨부 기능을 추가
일부 게시판을 파일 첨부 할 수 있도록 권한과 종류를 선택할 수 있는 기능
구현 방법에 대해서는 토의 해야할 필요성이 있음.

**Comment by baemoc** [comment]
super 관리자 : 사이트별로 파일업로드 기능 On/Off 설정, 업로드 파일 1개당 최대용량 설정
(사이트 관리에서 사용가능)
site & group 관리자 : 카테고리별 업로드 권한 & 다운로드 권한을 회원등급으로 설정
(뉴스 - 분류관리에서 사용가능)

파일 업로드 갯수는 1개면 되나요?

**Comment by aeroitems** [comment]
파일 업로드는 1개로 제약을 두는게 어떨까합니다.

**Comment by baemoc** [comment]
수정사항
1. 자신의 글에는 분류의 권한에 구애받지 않게 수정.

테스트 요청사항
1. 관리자로 접속후, 뉴스 분류의 업로드/다운로드 권한을 수정
2. 카테고리 선택후 업로드가 회원등급별로 잘 되나요?
3. 카테고리 내에서 다운로드가 비회원, 회원등급별로 잘 되나요?
4. 자신의 글의 다운로드가 분류권한에 구애받지 않고 잘 되나요?
5. 다운로드한 파일이 정확한 파일이 맞나요? 파일명이 제대로 되어있나요?
6. 슈퍼관리자로 접속후, 사이트의 업로드최대용량 변경하여 업로드제한이 잘 되나요?
7. 슈퍼관리자로 업로드 ON/OFF 설정후, 파일첨부가 나타나고 없어지나요?
(다른 테스트도 부탁드리겠습니다.)

**Comment by jejoongkim** [comment]
파일 첨부 기능 테스트해보니 잘 올라갑니다. 다운로드 해보니 올린 파일이 맞습니다.

**Comment by aeroitems** [comment]
테스트 중 입니다.

**Comment by aeroitems** [comment]
1. 관리자 접속후 뉴스 분류의 업/다운로드 권한 수정
   
   권한 수정 됨 - 확인됨

**Comment by aeroitems** [comment]
1. 회원등급별 업로드 

1) 권한이 없는 회원의 파일 업로드 시도 - 
업로드할 파일을 선택후 글을 올릴수 없음, 업로드 파일 삭제나 제거를 위한 별도의 버튼이 필요할 것으로 생각됨. 현재는 파일 선택을 다시 한뒤 취소해야 올릴수 있음

2) 권한 없이 업로드 - 하위 권한으로 업로드 시도 
- 결과 : 업로드 안됨 - 정상

3) 권한 가지고 업로드 
- 권한을 가지고 업로드 시도 (허용용량2MB로 시도) - 결과 업로드 됨 - 정상

4) 권한 가지고 허용량 초과 업로드 
- 권한을 가지고 허용량을 초과하여 업로드 시도(2.3MB) - 업로드 안됨 - 정상

5) 상위 카데고리에는 허용되지 않는 권한이나 하위 카데고리에서는 
    허용되는 권한으로 하위 카데고리 업로드 시도 
- 업로드됨 - 정상

6) 하위 카데고리에서는 허용되나 상위 카데고리에서는 허용되지 않는
    권한으로 상위 카데고리에 업로드 시도 
- 업로드 안됨 - 정상

7) 사이트에 업로드 OFF 후 업로드 시도
- 업로드 버튼이 보이지 않음 - 정상

**Comment by aeroitems** [comment]
1-1 회원 등급별 다운로드
1) 업로드 권한이 없어진(OFF 된) 사이트에 업로드된 파일의 다운로드
- 다운로드 됨 - 정상

2) 다운로드 권한이 없는 회원의 다운로드
- 다운로드 권한이 없습니다. - 정상

3) 다운로드 권한은 없으나 본인이 올린 파일
- 다운로드 됨 - 정상

4) 비회원에게 다운로드 권한 부여후 다운로드
- 다운로드 됨 - 정상

5) 회원에게 권한 부여후 비회원으로 다운로드
- 해당 카데고리에 다운로드 권한이 없습니다. - 정상

**\* 참고 일반 사용자의 경우 현재 나의 권한이나 레벨이 어느정도인지 확인할 수 있는 곳이 없음
**\* 일반 사용자의 경우 게시판에도 권한별 사용 가능 안내를 확인할 곳이 없음.

**Comment by aeroitems** [comment]
1. 카테고리 내에서 다운로드가 비회원, 회원등급별로 잘 되나요?
2. 회원 등급별 다운로드 테스트 - 완료(정상)
3. 자신의 글의 다운로드가 분류권한에 구애받지 않고 잘 되나요?
4. 자신의 글은 권한이 없어도 다운로드 가능함.  - 정상
5. 자신이 등록한 글은 권한이 없어도 읽기 가능함. - 확인필요
6. 다운로드한 파일이 정확한 파일이 맞나요? 파일명이 제대로 되어있나요?
7. 한글 파일이름 공란 포함 - 공란은 언더바(_)로 치환되어 업로드되고 다운로드에서도 공란이 언더바로 변경된 상태로 다운로드됨 - 허용 범위내(정상)
8. 슈퍼관리자로 접속후, 사이트의 업로드최대용량 변경하여 업로드제한이 잘 되나요?
9. 1MB로 변경하여 업로트 수행 - 업로드 안됨 - 정상
10. 5MB로 변경하여 업로드 제한 - 5MB 이하 파일 업로드 됨 / 5MB 이상의 파일 업로드 안됨 - 정상
11. 슈퍼관리자로 업로드 ON/OFF 설정후, 파일첨부가 나타나고 없어지나요?
12. 업로드OFF 시 - 글 작성시 업로드 버튼 나타나지 않음 / 기존의 업로드된 파일은 다운로드 가능함 - 정상
13. 업로드ON 시 - 글작성시 업로드 버튼 나타남  - 정상
