### ISSUE TITLE
콘텐츠와 이북에 0원 상품 등록 추가?

### ISSUE THREAD

**Issue by aeroitems** [netnamu/zinpack#24]
콘텐츠와 이북에 무료 상품을 추가 할 수 있도록 해야할 까요?
아니면 현행 99포인트 이상을 유지하도록 하는게 맞는걸까요?
의견 주세요.

**Comment by baemoc** [comment]
제 생각은 무료가 있는게 좋을 것 같습니다.
무료만으론 수익은 안나겠지만,
이북체험을 해보거나 데모버전을 통한 이북판매가 이루어질 수 있겠네요.

**Comment by aeroitems** [comment]
무료 기능을 그럼  추가하기로... 하죠.

**Comment by baemoc** [comment]
수정사항
1. 무료의 경우, 추후에 유료로 변환하여도 구매내역에 존재하므로 무료로 계속 이용가능!!
2. 컨텐츠의 경우만 다운로드 기한이 존재함.

테스트 요청사항
1. 무료 컨텐츠 및 이북 등록/수정
2. 무료의 경우에도 구매내역에 나타나나요?
3. 포인트가 없어도 무료컨텐츠를 구매할 수 있나요?
(부가적인 테스트도 부탁드리겠습니다.)

**Comment by aeroitems** [comment]
2014-08-26 테스트 시작 - eBook 테스트
1. 무료 이북 등록 - 확인됨
   무료 이북 콘텐츠를 등록한다(ID : fantaya@gmail.com)
2. 무료 이북 구입 / 확인 - 확인됨
   등록 후 관리자 ID로 로그인 구입(cto@info-way.co.kr)
   무료로 수정된 도서 추가 구입
   유료 도서 구입
   목록 보기와 내용 검토 
3. 포인트 없이 이북 구입 - 확인됨
   2개의 ID에거 각각 포인트 없이 이북 구입
4. 이북 구입후 유료로 수정후 재 구입하기
   구입후 가격 변경 0 -> 99 
   재 구입 시도
   결과 : 0포인트로 계산되어 다운로드 됨
5. 유료로 전환후 구입하기 - 확인됨
   이전에 구입한 적이 없는 사용자의 ID를 이용해 구입 시도
   결과 : 구매시 유료로 결재됨 (99pt)
6. 유료구매후 다시 재구매 시도하기 - 확인됨
   유료로 결재한 페이지를 뒤로 기능을 이용해 후퇴 후 재 결재 시도
   결과 : 포인트가 추가로 차감되지 않음

**Comment by aeroitems** [comment]
http://www.ifwy.net/super 
수퍼 관리자 페이지를 참조하여 테스트 작업하시기 바랍니다.

**Comment by jejoongkim** [comment]
외국잡지를 등록해본 결과 0원으로 등록 됩니다.

**Comment by aeroitems** [comment]
콘텐츠 등록 시험을 부탁드려요.

**Comment by aeroitems** [comment]
콘텐츠몰 0원 등록 기간 테스트는 완료 되지 못했으나 다른 기능은 확인됨 모두 통과 
릴리즈 요청함.
