### ISSUE TITLE
뉴스게시판 혹은 대문페이지 인기뉴스에 대한 시한 조절 필요성

### ISSUE THREAD

**Issue by jejoongkim** [netnamu/zinpack#25]
인기뉴스의 시한이 처음부터 그냥 누적이냐.... 아니면 시한이 정해져 있느냐에 대한 이슈 등장

고객사의 의견은 약1주일 이내의 인기뉴스로 했으면 한다.  방문자수가 많아지면 이후 3일, 1일로 조정이 필요할 듯 하다는 의견

**Comment by aeroitems** [comment]
어떤 사이트의 요구 사항인가요?
일단 대부분은 게시물 많아지고 방문자수 많아지면 그냥 누적으로만 해도 인기 기사는 자연스럽게 변화하거든요. 게시물이 많지 않고 방문자수가 적으면 매일 그게 그거인 상황이 되긴 하죠.

**Comment by jejoongkim** [comment]
시한이 정해지는게 필요할 듯 합니다. 예를 들어 어떤 기사가 1000클릭이었는데 반년이 지나도 다른 기사들이 900, 800번 클릭이다 그러면 반년동안  1000번 짜리 기사가 쭉 올라와 있는 현상이 벌어집니다.

**Comment by aeroitems** [comment]
기사 올리기가 활발하고 독자들이 많다면 한기사가 계속 남아 있는 현상은 거의 없어집니다.
그러나 독자가 많지 않은 구조라면 필요할 수 있다고 생각됩니다.
이슈 회의때 자세히 논해보기로 하죠.

**Comment by jejoongkim** [comment]
월간항공의 인기기사를 보면 6월달 기사가 아직도 올라가 있습니다. 이는 수정이 필요할 듯 하며, 인기뉴스 시한에 대한 의견이 브로마이드에서 재 제안되었습니다.

**Comment by baemoc** [comment]
매월 인기 조회수가 리셋되도록 변경하였습니다.

**Comment by jejoongkim** [comment]
확인 하였습니다. 클로즈 합니다
