### ISSUE TITLE
안드로이드 인터넷 브라우저 실행시 이북에서 aerospace 로고가 보이지 않는 현상

### ISSUE THREAD

**Issue by jejoongkim** [netnamu/zinpack#26]
갤럭시s2 HD LTE 인터넷 브라우저로 월간항공 이북 미리보기 해봤습니다.
이북 썸네일 이미지들 위에 빨간색으로 표시되는 Aerospace 영문 로고가 안보입니다.

솔이씨 핸펀으로 점검이 필요할 듯 합니다. 기계자체의 오류인지 아니면 안드로이드의 문제인지.

안드로이드 문제일 경우 안드로이드 태블릿도 같은 증상을 보이지 않을까요?

집중 점검 결과 
아이패드(사파리,크롬) - 정상동작
아이폰 - 사파리 정상동작, 크롬은 이미지 슬라이드 동작안됨
갤럭시 - 정상동작 - 그러나 위에 로고 안보임

**Comment by baemoc** [comment]
이북 브라우저 상단 로고 수정 완료!

**Comment by jejoongkim** [comment]
Great!! 수고하셨습니다.

**Comment by aeroitems** [comment]
설정상의 문제였고 수정되었습니다. 2.4에 반영될 예정입니다.

**Comment by aeroitems** [comment]
이슈 클로즈 합니다.
