### ISSUE TITLE
갤럭시폰에서 웹에디터 모드가 올바르게 작동하지 않음

### ISSUE THREAD

**Issue by aeroitems** [netnamu/zinpack#27]
갤럭시 폰의 웹 브라우저에서 뉴스 작성시 웹에디터 모드가 올바르게 작동하지 않고 한줄의 빈칸으로만 나타남.
간편모드는 올바르게 작동함

**Comment by baemoc** [comment]
저희가 쓰고 있는 ckeditor는 5버전에 모바일 지원이 되도록 개발하고 있다고 합니다.
하지만 언제 출시될지는 미정이라고 합니다.

전에 썼던 위지윅 웹에디터 입니다. 안드로이드에서 되는지 확인 부탁드립니다.
http://www.webnote.kr/
