### ISSUE TITLE
갤럭시 폰에서 사진 업로드가 안됨

### ISSUE THREAD

**Issue by aeroitems** [netnamu/zinpack#28]
메인슬라이드를 수정하려고 관리자 모드에서 파일 찾기를 누르면 아무런 작동을 하지 않음
아이폰과 아이패드에서는 정상적으로 작동함.

**Comment by baemoc** [comment]
테스트할 안드로이드 기기가 필요합니다.

**Comment by jejoongkim** [comment]
딸내미껄론 되는데요, 갤럭시에서는 그 대신  웹에디터모드는 안 열리네요

**Comment by aeroitems** [comment]
갤럭시S4에서 확인 
정상적으로 작동함. 기본 브라우저의 문제 크롬으로 해결.
