### ISSUE TITLE
RSS 뉴스피드 아이콘 제작 요먕

### ISSUE THREAD

**Issue by aeroitems** [netnamu/zinpack#29]
RSS 뉴스피드 아이콘 제작 요망

**Comment by leihaht** [comment]
글쓰기 버튼 옆에 들어가려면 fontawesome 형식의 아이콘이 들어가야됩니다.
http://fontawesome.io/cheatsheet/
여기 사이트에서 rss 로 검색하시면 쓸수있는 아이콘이 두개 나오는데, square 박스가 없는 아이콘을 추천드립니다. 현재 사이트 디자인에서 아이콘들이 박스가 없는 아이콘이 쓰여서이고요.
적용하실때는 버튼의 class를 바꿔주시기만하시면 되요.
