### ISSUE TITLE
사이트 하단 - 위지윅 에디터로 변경

### ISSUE THREAD

**Issue by baemoc** [netnamu/zinpack#30]
사이트 하단 내용을 자유롭게 변경가능.

**Comment by baemoc** [comment]
© INFOWAY GLOBAL Corp.  <- 이 곳에 zinpack.com 으로 이동하게끔 링크 적용.

**Comment by aeroitems** [comment]
위지윅 에디터 테스트 완료.
무리한 테스트는 하지 않았음.
브랜드 로고는 월간 오디오에서 가져다가 사용하였음.
프랜드 로고를 표 내부에 넣어 모바일에서도 테스트 완료 잘 보이고 잘 줄어들음

**Comment by jejoongkim** [comment]
감사합니다. ~  첵크했습니다.

**Comment by aeroitems** [comment]
완료
