### ISSUE TITLE
모바일로 보았을때 기사 짤림 현상

### ISSUE THREAD

**Issue by jejoongkim** [netnamu/zinpack#32]
http://www.zinpack.com/bbs/m/mcb_data_view.php?type=mcb&ep=ep1703345223537c13348795b&gp=gp49892612753f4694c22f12&item=md74517857653fb486c91a4b

모바일로 보았을때 아래부분 기사 짤림

**Comment by aeroitems** [comment]
확인하였습니다.
반영 버전에 대한 협의는 다음주 월요일 형상위원회 회의때 결정하도록 하겠습니다.

**Comment by jejoongkim** [comment]
해결됨. 유튜브 소스문제
