### ISSUE TITLE
이북 구독시 팅김 현상

### ISSUE THREAD

**Issue by jejoongkim** [netnamu/zinpack#33]
진팩.컴에 이북을 pdf로 등록해보고 미리보기 기능을 통해 아이패드로 보던중

그냥 바탕화면으로 팅겨나가는 현상이 계속 됩니다.

**Comment by jejoongkim** [comment]
테스트페이지의 외국잡지 이북으로 테스트해본 결과 default 배수에서는 잘 되나.. 확대 +를 한두번 누르고 위아래로 보면서 넘길시 팅 하고 팅김...(아이폰)

**Comment by jejoongkim** [comment]
아이패드 십수번 테스트 결과 사파리 브라우저에서 확대 여부와 관계 없이 보다가 보면 바탕화면으로 팅김

**Comment by aeroitems** [comment]
확인 해 보겠습니다.

**Comment by baemoc** [comment]
메모리를 초과하여 나타나는 현상 같습니다.

**Comment by jejoongkim** [comment]
전원은 껐다가 켜봤는데 그렇게 하면 해결이 안되는건가요

**Comment by baemoc** [comment]
스마트폰이나 테블릿의 브라우저는 하나의 앱이고
앱의 일정 메모리가 초과되면 앱이 죽습니다.
그래서 바탕화면으로 튕기죠.
리소스를 적게 먹는 PDF뷰어가 필요합니다.
재부팅과는 관련이 없습니다.

**Comment by jejoongkim** [comment]
재시험결과 게임 큰거 몇개 지우고 메모리 정리 앱으로 메모리 정리 돌리고 실험해보니
사업계획서는 잘 돌아갑니다. 그러나 크키가 큰 외국잡지는 여전히 중간에 팅기는 군요

**Comment by aeroitems** [comment]
이슈 #34 와 합칩니다.
