### ISSUE TITLE
갤럭시 기본 브라우저에서 pdf 이북 구현 안됨

### ISSUE THREAD

**Issue by jejoongkim** [netnamu/zinpack#34]
갤럭시 s2 hd lte 기본 브라우저에서 pdf 형식의 이북 (외국잡지, 사업계획서) 구현이 안됩니다.

한지민의 필리핀도네이션북과 1만시간의 법칙은 구현 됩니다.

**Comment by aeroitems** [comment]
되는것과 안되는 pdf 파일의 형식의 차이점을 우선 확인해봐야겠습니다.

**Comment by baemoc** [comment]
제가 예상하기로는 pdf의 차이보다는 스마트폰의 메모리부족 현상 같습니다.

**Comment by aeroitems** [comment]
구글 뷰어를 이용하는 방법은 어떨까요?
https://docs.google.com/gview

다른 PDF 뷰어도 고민해봅시다.
https://www.udemy.com/blog/html5-pdf-viewer/

**Comment by baemoc** [comment]
테스트용 PDF 링크
http://www.ifwy.net/book/infoway/all/bd62101540653fc77e768204/bd62101540653fc77e768204.pdf

**Comment by aeroitems** [comment]
구글뷰어 시험 결과 공유나 별도 다운로드 기능이 버튼으로 자리 잡고 있어서 적합하지 않다고 판단됩니다. 또한 이 정도 사이즈의 파일을 읽지 못하는 군요. 현재 진팩에서 채택하고 있는 리더보다 한참 떨어집니다.

다른 리더들을 시험해 봐야하겠습니다.

**Comment by leihaht** [comment]
다른 pdf 뷰어를 찾기 전에 pdf 뷰어에서 꼭 필요한 기능들을 정리하는것도 좋을것 같습니다.
저번 회의에서 나온 말로는,
- 줌기능
- url이 노출되지않아야함
- 프린트(옵션)

이렇게 있는데, 여기에서 추가로 전체화면 모드, 페이지 검색 등등 여러가지가 있겠네요.
참고로 pdf 뷰어 자바스크립트로 검색해보니 여러가지가 나옵니다.
http://www.jqueryrain.com/2012/09/best-jquery-pdf-viewer-plugin-examples/

**Comment by aeroitems** [comment]
브라우져를 점검해서 모바일 이면 브라우져에서 pdf 기본 보기로 보이도록 하고 현행 뷰어는 PC 버전에서만 유지되도록 수정

**Comment by baemoc** [comment]
브라우저의 기본 뷰어로 변경하여도 똑같은 현상.
파일의 크기로 인한 문제로 보입니다.
모바일에서 구동되는 PDF파일의 사이즈 최대치를 검토해야 합니다.

**Comment by aeroitems** [comment]
이번 2.4.1 업데이트에서는 PDF 뷰어 수정은 제외하겠습니다.
뷰어의 문제가 아니네요.

다음중 하나의 방법을 도입해야하지 않나 싶습니다. 의견주세요.
1. PDF 파일을 보여주는 방식을 이미지 변환후 보여주는 형태로 전환
2. PDF 파일의 상한선을 제한하여 여러개의 작은 파일로 나누어 올리는 방법
