### ISSUE TITLE
익스플로러 월간항공 이북 볼때 썸네일 6개만 보임

### ISSUE THREAD

**Issue by jejoongkim** [netnamu/zinpack#35]
데스크톱에서 이북을 볼때 크롬에서는 오른쪽에 바가 나와서 아래로 내려 볼 수 있으나

익스플로러로 월간항공 판매중인 이북을 미리보기 해볼경우 위6개 썸네일만 보이고 오른쪽에 바가 나오지 않아 아래에 있는지 알기 어렵습니다.

화면을 축소하면 9개가 다 나옵니다.

**Comment by aeroitems** [comment]
확인하였습니다.

**Comment by baemoc** [comment]
노트북에서 화면이 작아서 짤려보이는 것 같습니다.
익스플로러에서 스크롤바와 창크기 조절을 활성화 했습니다.

**Comment by jejoongkim** [comment]
수고하셨습니다
