### ISSUE TITLE
검색 막대기 디자인 수정 필요

### ISSUE THREAD

**Issue by jejoongkim** [netnamu/zinpack#36]
검색 막대기가 앞 부분이 짤리면서 약간 어긋나 있습니다. 
위아래 정렬을 하거나
아님 화면 위 전체를 덮도록 수정이 되야 할 듯 합니다.

**Comment by leihaht** [comment]
모바일 화면으로 전환될때 왼쪽 부근에 약간 어긋나는 현상 확인.
가로 사이즈 css가 inherit 로 되있어서 상위 css를 그대로 가져와서 나타나는 현상으로 확인.

현재 html 구조로는 깔끔하게 처리가 안되서 javascript를 수정해야되네요.
searchbox가 스크롤되서 안보여서 위에 다시 나타나게될때 javascript를 통해 html 코드를 수정함.

**Comment by baemoc** [comment]
테스트 사이트에 소스 적용하였습니다.
