### ISSUE TITLE
회원가입 등록 정보

### ISSUE THREAD

**Issue by leihaht** [netnamu/zinpack#37]
현재 zinpack에서 회원 가입을 할때,
- 아이디(이메일)
- 비밀번호
- 이름(실명)
- 닉네임
- 보조이메일
- 핸드폰번호
- 주소
- 이용약관 동의
- 개인정보취급방침 동의

이렇게 있는데요. 여기에서 핸드폰번호와 주소가 한국핸드폰, 한국주소를 넣어야되는데
이 정보가 회원등록할때 꼭 필요한지 알고싶습니다. 해외에서 가입을 할때는 이 정보가 없어서 넣을수가 없네요.
그리고 이메일을 아이디로 쓰는 이유도 알고싶습니다. ProcessWire로 이전할때 아이디와 이메일이 따로 등록되거든요.

**Comment by aeroitems** [comment]
1. 이메일 아이디
   국내 서비스를 할때 본인인증에 관련된 법률이 변경되어서 개인 식별정보를 주민 번호로 받을 수 없게 되어 있습니다. 그러다 보니 본인 인증을 위해서 이메일 주소를 개인 식별자로 사용하고자 아이디로 사용하고 있습니다.
2. 한국 주소 입력
   주소 문제는 한국 주소와 외국 주소를 나누어 선택하여 입력 가능하게 만들어야 할 듯 합니다. 반드시 꼭 필요하다고 볼 수는 없네요. 그러나 배송이나 기타 지역 정보등을 확인 하기 위해서 필요로 할 듯 합니다. 반드시 필요로 하는지는 다음 월요일 회의때 논의 해보도록 하지요.
   가입을 신속하게 하기 위해서는 배송을 해야할 상황이 발생할 때  입력 받는다던지 최소화 시킬 필요성은 있다고 생각됩니다.

**Comment by leihaht** [comment]
이메일을 로그인 아이디로 쓰이는곳은 많이 있긴한데요.
개인적으로 이메일과 로그인 아이디는 구분하는걸 선호합니다.

주소 입력은 회원 가입할때 의무적으로 하기보다는 배송정보 입력할때 주소를 입력하거나 이미 입력한 주소를 불러들여 적용하는건 어떨까해요.

핸드폰도 주소와 같은 형식으로 배송주소 입력할때 입력 받는건 어떨까 합니다.

물론 이렇게 되면 주소와 핸드폰 정보를 가입후 계정정보에서 따로 입력 가능하게도 해야겠죠.

현재 zinpack 3.0 개발에서 회원 가입관련해서 기획하는중인데 회의에서 의논해봤으면 해요.

**Comment by leihaht** [comment]
주소와 전화번호는 배송정보 입력할때 입력하거나 회원가입 후 입력 받는것으로 함.
특별히 문제가 되지않는 이상, 이메일로 로그인하는것에 대해서는 유지하기로 함.

ProcessWire에서 이메일로 로그인하는 방법은 약간의 코드를 수정하면 문제없이 되는것으로 확인 함.

**Comment by aeroitems** [comment]
최이사님의 건의로 시작이 되어 개인 정보 수집에 대해 좀더 알아보게 되었네요.
최종 확인을 더 해봐야하긴 하지만 지금 개인정보보호법에서 개인 전화번호를 수집하는 것도 제한한다고 합니다. 따라서 개인 정보의 최소한의 수집이라는 것은 이번에 반드시 정리하고 넘어가야 할 듯 합니다.
