### ISSUE TITLE
웹에디터모드에서 글 올릴때 이미지 싸이즈에 대한 문의

### ISSUE THREAD

**Issue by jejoongkim** [netnamu/zinpack#39]
월간 브로마이드 토크 그룹의 경우 일반 10대 학생들이 들어와서 이미지와 글을 올리게 프로모션 이벤트를 진행할 예정입니다.

폰에서 올리면 간편모드가 default로 주어지지만 PC로 올리는 경우도 많을것인데 PC로 올릴때 전에 문제가 되었던 이미지 싸이즈에 대한 것을 일반 독자들은 모를 터, 

일일이 공지를 하거나 일일이 수정을 할 수도 없을 것이고 이에대한 문제가 제기 되었습니다. 

PC에서도 일단 간편모드를 default 로 주는 방법을 쓰던지.

아니면..웹에디터에서 이미지를 올릴때 해결할 방안을 찾아야 할 듯 합니다.

**Comment by aeroitems** [comment]
일단 가장 빠른 방법은 간편모드를 PC의 기본으로 하는 것
이 될 수 있겠네요.
에디터에서 사진 업로드에 관련된 문제는 에디터를 좀더 연구하던가 다른 대치에디터를 구하던가 해야할 듯 합니다. 여기에 대한 의견을 부탁드리구요. 이 사안은 월요일 회의때 자세히 논의하겠습니다.

**Comment by baemoc** [comment]
전에 썼었던 위지윅웹에디터의 경우에는
이미지 사이즈를 외부에서 컨트롤할 수 있었습니다.
어떤 이유로 웹에디터를 교체했었던건지는 기억이 안납니다^^;;;

**Comment by aeroitems** [comment]
html 코드를 올바르게 인식 못한다는 것과 엔터를 자기 맘대로 늘리고 줄이는 문제가 있어서 이쁘게 편집이 안되는 문제가 있어서 변경을 하였던것으로 기억합니다.
당시 상당히 심각한 문제여서 이미지사이즈 변동에 대한 문제가 있음에도 불구하고 넘어온것이죠.
에디터 문제도 최대한 찾아보고 월요일 논의 했으면 합니다.

**Comment by aeroitems** [comment]
간편모드를 기본으로(PC, 모바일 모두) 하고 웹에디터를 별도로 선택하도록 수정
다음의 문구를 웹에디터 옆에 추가
(모바일 미지원)

**Comment by aeroitems** [comment]
PC에서 간편모드가 기본으로 설정됨 - 확인됨 정상
모바일에서 (모바일 미지원) 메시지 표시됨 간편모드 기본 - 정상
이슈 클로즈 함.
