### ISSUE TITLE
결재시 부가세 과세 여부

### ISSUE THREAD

**Issue by aeroitems** [netnamu/zinpack#40]
도서의 경우 면세 품목이라 결재시 비과세로 처리해야 부가세를 내지 않습니다.
등록시 비 과세 품목을 등록해서 부가세를 면제하는 기능이 필요합니다.
현행으로는 10%의 부가세를 우리만 지불하도록 되어 있어서 10%의 수수료를 그냥 세금으로 다 날리게 되어 있네요.
이에 대한 빠른 변경이 필요할 듯 합니다.

**Comment by baemoc** [comment]
PG사에 부분면세를 신청하였고,
부분면세에 대한 내용은 연락을 따로 준다고 합니다.

**Comment by aeroitems** [comment]
네 알겠습니다.

**Comment by baemoc** [comment]
상품등록시 상품옵션마다 면세 상품 여부를 선택하고,
결제 시에 결제 총금액과 면세상품의 금액을 파라미터로 PG사에 던져주면 된다고 합니다.

**Comment by baemoc** [comment]
테스트 요청 드립니다.
이 건은 결제에 대한 부분이기에
테스트사이트가 아닌 운영중인 사이트에서 테스트해주시기 바랍니다.

1.상품등록에서 옵션의 면세상품 선택후 저장.
2.면세상품과 부가세포함 상품을 결제.
3.LG U+전자결제 사이트에서 면세되었는지 확인.

**Comment by aeroitems** [comment]
월간항공에 적용하였습니다.
결재 시행에 대한 확인 바랍니다.
