### ISSUE TITLE
배송비의 결재 수수료 면제

### ISSUE THREAD

**Issue by aeroitems** [netnamu/zinpack#41]
다른 판매처에 알아보니 배송비는 결재PG사에서 수수료를 면제해준다고 합니다.
그래서 수수료를 아끼기 위해 배송비를 항상 일부러 청구하는 곳도 있다고 하는데 확인해봐야 할 것 같습니다. 만약 배송비 수수료 면제를 할 수 있다면 적용하여 수수료를 절약 할 수 있었으면 좋겠습니다.

**Comment by baemoc** [comment]
배송료의 결재수수료는  PG사에서 처리하는 부분이 아니라고 합니다.

**Comment by aeroitems** [comment]
확인 되었습니다.
