### ISSUE TITLE
공지사항에 sns공유버튼 수정

### ISSUE THREAD

**Issue by baemoc** [netnamu/zinpack#44]
공지사항에 sns 공유 버튼이 구버전으로 되어있음.

**Comment by baemoc** [comment]
공지사항 위지윅 웹에디터로 변경.
sns 공유 최신버전으로 수정.

**Comment by jejoongkim** [comment]
테스트 해봤습니다. 훨 씬 좋은데요..공지사항에 에디터가 적용되니 활용도가 더 높아질 듯 합니다. 이미지도 넣고~

**Comment by aeroitems** [comment]
웹에디터로 그림 등록 하였으나 브라우져 폭을 줄일때 그림이 줄어들지 않음 - 반응형으로 작동하지 않음
동일한 내용을 뉴스로 등록 하면 정상적으로 줄어듬 

공지 사항에 등록한 내용 - 폭을 줄이면 큰 이미지가 줄어들지 않음
http://www.ifwy.net/bbs/m/all_notice_view.php?type=mcb&ep=ep17561325175213172de4b13&gp=all&idx=11

같은 내용을 뉴스에 등록 - 폭을 줄이면 큰 이미지가 자동으로 줄어들게됨
http://www.ifwy.net/bbs/m/mcb_data_view.php?type=mcb&ep=ep17561325175213172de4b13&gp=all&item=md96560340454064d4324c0a

**Comment by leihaht** [comment]
이미지를 반응형에 맞게 class를 추가해야됩니다.

```
<img src="이미지 소스" class="img-responsive">
```

**Comment by baemoc** [comment]
수정 완료

**Comment by aeroitems** [comment]
시험 완료 확인됨
