### ISSUE TITLE
아이디/비밀번호 찾기

### ISSUE THREAD

**Issue by leihaht** [netnamu/zinpack#45]
현재 zinpack에서 아이디/비밀번호 찾기를 하면
이메일(로그인아이디)와 이름을 입력하게 되있던데요.

이름이 어떤 이름인가 알고싶습니다. 이것이 실명으로 등록된 이름을 말하나요?

그리고 아이디 찾기와 비밀번호 찾기가 구분되야된다고 생각해요.
zinpack 3.0 작업하다가 이부분이 확실하지가 않아서 이슈로 남깁니다.

**Comment by aeroitems** [comment]
말씀대로 아이디와 비번 찾기는 분리 되어야 합니다.
