### ISSUE TITLE
메인슬라이드/배너 슬라이드 1개일 경우 화살표 안보이도록 변경

### ISSUE THREAD

**Issue by aeroitems** [netnamu/zinpack#48]
슬라이드가 1장일 경우 화살표가 나타나지 않도록 해주세요.

**Comment by leihaht** [comment]
### 슬라이드 박스

1개일때 화살표 및 dot 표시 안나오게하는방법 -> php에서 이미지 갯수를 세어서 1개일때 화살표 및 dot 표시 부분의 html 코드를 출력하지않게해야됨.

**Comment by leihaht** [comment]
추가 이슈로
화살표가 평상시에는 안보이지만 마우스 올려놓으면 나타나는건 css 스타일로 처리가 가능하며, 수정본을 이메일로 보냈습니다.

**Comment by aeroitems** [comment]
네 알겠습니다. 수고하셨습니다.

**Comment by jejoongkim** [comment]
수고 많으셨습니다
