### ISSUE TITLE
쇼핑몰 상품설명 길다란 이미지 삽입 불가 

### ISSUE THREAD

**Issue by jejoongkim** [netnamu/zinpack#49]
에디터에 쇼핑몰 설명용 위아래로 긴....이미지를 삽입할 수 없는 문제를 수정 필요합니다.

**Comment by baemoc** [comment]
ckfinder 내의 config에서 maxWidth와 maxHeight 수정으로 해결.

**Comment by leihaht** [comment]
흠? 역시 CKfinder 사용하신거군요.
CKfinder 그거 유료던데 구입하신건가요?

**Comment by aeroitems** [comment]
CKfinder 에서 배이사님의 직접 프로그래밍으로 변경
