### ISSUE TITLE
배송비 무료 설정

### ISSUE THREAD

**Issue by jejoongkim** [netnamu/zinpack#50]
6만원 이상 혹은 5만원 이상은 배송비 무료 설정이 필요합니다.

**Comment by baemoc** [comment]
한 사이트 내에서 장바구니의 상품 누적 금액은 아닐 것이고,
판매자별로 나뉜 상품누적금액일 것으로 보입니다.
즉, 상품별로 따로 조절할 것은 없고 판매자별로 한번씩 조절하면 됩니다.

*의견
[판매자 정보] 에 초과금액 배송비 무료에 대한 항목을 만들고,
on/off 형식으로 하여, on을 하고 금액을 입력하면 될 것 같습니다.

**Comment by jejoongkim** [comment]
좋은 아이디어 이십니다. 현재 판매자별 배송비 무료에 대한 니즈가 계속 제시되고 있습니다.

금액별로 배송비를 무료로 할 수 있도록 하는 것 좋을 것 같습니다.
