### ISSUE TITLE
시급한 버그 보고 및 수정 요청

### ISSUE THREAD

**Issue by jejoongkim** [netnamu/zinpack#52]
1. 로그 인이 안되있는 상태에서 글쓰기 누르면 글쓰기 화면이 나타남
   
   단, 제목, 내용, 이미지 기록은 되나 카테고리 선택이 되지 않아 실제로 글을 쓸 수는 없슴.
2. bromide 싸이트는 가입되어 있고 로그인 한 상태의 경우임.
   
   TALK 그룹은 가입되어 있지 않은 상태임
   
   TALK가 공개 그룹이라 게시물은 볼 수 있슴. 게시물을 보다가...
   
   글을 쓰기 위해 글쓰기 단추를 누르면 "그룹에 가입해 주세요" 메시지가 뜨고 확인을 누르면 그룹가입 페이지로 가야 하는 사황이나....
   
   "로그인 후 이용해주세요"  가  뜸. 확인 단추를 누르고 나서 다시 글쓰기 누르면 또 로그인후 이용해주세요 라고 또 뜸.
   
    따라서 처음 이용하는 사람은...엉? 로그인 되어 있는되 왜 계속 로그인 하라고 하지? 라고 하는 상황임.
3. 어쨌던 메시지 무시하고 그룹 가입단추를 찾아서  자동가입을 하고 나니...
   
   화면이 관리 화면으로 넘어가 버림.  (뉴스 페이지나 글쓰기 페이지로 넘어가야 할 듯 함)
   
   상기 사항은 매우 시급한 사항이라 개발이사에게 개별로 보고하고 수정 요청을 한 상황임.

**Comment by leihaht** [comment]
중복이슈 #53
