### ISSUE TITLE
시급한 버그 보고 및 수정 요청

### ISSUE THREAD

**Issue by jejoongkim** [netnamu/zinpack#53]
1. 로그 인이 안되있는 상태에서 글쓰기 누르면 글쓰기 화면이 나타남
   
   단, 제목, 내용, 이미지 기록은 되나 카테고리 선택이 되지 않아 실제로 글을 쓸 수는 없슴.
2. bromide 싸이트는 가입되어 있고 로그인 한 상태의 경우임.
   
   TALK 그룹은 가입되어 있지 않은 상태임
   
   TALK가 공개 그룹이라 게시물은 볼 수 있슴. 게시물을 보다가...
   
   글을 쓰기 위해 글쓰기 단추를 누르면 "그룹에 가입해 주세요" 메시지가 떠야하나
   
   "로그인 후 이용해주세요"가 계속 뜸
   
    따라서 처음 이용하는 사람은...엉? 로그인 되어 있는되 왜 계속 로그인 하라고 하지? 라고 하는 상황임.
3. 어쨌던 메시지 무시하고 그룹 가입단추를 눌러서 자동가입을 하고 나니...
   
   화면이 관리 화면으로 넘어가 버림.  (뉴스 페이지나 글쓰기 페이지로 넘어가야 할 듯 함)

상기 사항은 매우 시급한 사항이라 개발이사에게 개별로 보고하고 수정 요청을 한 상황임.

종전 팻치 전에는 발생하지 않았던 오류로 현재 bromide사이트에서는 TALK 게시판에 글을 올려달라고 프로모션을 진행하고 있는데 지금 상황은 글을 쓸 수 없는 상황이 되어 있으므로 매우 시급한 사항으로 사료됨.

**Comment by baemoc** [comment]
1. 로그인이 안되었을 경우, 로그인 페이지로 이동.
2. 그룹회원이 아닐경우, 그룹가입 페이지로 이동.
3. 그룹가입시 메인화면으로 이동.

바로 적용하였습니다.

**Comment by jejoongkim** [comment]
테스트 완료 했습니다. 이상없이 작동합니다. 수고하셨습니다.
