### ISSUE TITLE
웹 에디터에 대한 의견

### ISSUE THREAD

**Issue by leihaht** [netnamu/zinpack#54]
#### 현재 새로운 웹 에디터를 검색중입니다.

여러가지로 보고있지만 크게 두가지 형식이 있네요.
- WYSIWYG 형식의 웹에디터
- Markdown 웹에디터

이에 대한 의견을 추가로 듣고싶습니다.
#### WYSIWYG 형식의 웹에디터

지금 현재 zinpack에서 쓰이는 방법이고 말그대로 웹에디터에 작성하는데로 보여지는 형식이네요.
1. 장점
   - 사용자가 쉽게 글을 작성 및 수정할수있음
   - 기능들이 보통 아이콘으로 표시되어 쉽게 쓸수있음
2. 단점
   - 서버에 저장될때 html 코드 그대로 저장됨
   - 에디터 기능을 자바스크립트로 만들어져서 그에 따른 로딩 용량이 커짐

> 일반 사용자들이 사용하기 좋다.
#### Markdown 에디터
1. 장점
   - 서버에 markdown 형식의 텍스트로 저장이 될수있다. -> 서버에 저장될 텍스트가 줄어든다.
   - 기능들을 작성될 텍스트에 함께 쓰인다.
2. 단점
   - 기능들을 어떻게 써야되는지 배워야된다. -> 그리 어렵지 않지만 그래도 알아야된다.
   - 서버에서 글을 불러올때 html 형식으로 변환해야한다.

> 편집자들이 사용하기 쉽다.

**Comment by aeroitems** [comment]
저는 일반사용자 위주로 해야 된다고 생각됩니다. 많은걸 배우도록 만드는 인터페이스는 아직 일반인 들에게는 무리인듯 싶습니다.

**Comment by jejoongkim** [comment]
위지윅
