### ISSUE TITLE
관리모드에서 뉴스페이지로 가거나 할때 헷갈리다는 이슈

### ISSUE THREAD

**Issue by jejoongkim** [netnamu/zinpack#55]
일반인들의 경우 관리모드에서 다시 메인페이지로 찾아가기 힘들다는 이슈가 있습니다.
위에 싸이트 이름을 누르면 메인페이지로 돌아가게 해달라는 요청이 접수됨.

한참을 찾아야 네모 아이콘을 눌러서 돌아가는 걸 찾을 수 있다는 의견.

**Comment by baemoc** [comment]
테스트 사이트에 적용하였습니다.

**Comment by jejoongkim** [comment]
최곱니다

**Comment by jejoongkim** [comment]
테스트완료
