### ISSUE TITLE
뉴스 게재시 이미지 삽입할때 드래그 앤 드롭 지원의 건

### ISSUE THREAD

**Issue by jejoongkim** [netnamu/zinpack#56]
현장 실시간 뉴스 기재시 이미지 드로그 앤 드롭 기능에 대한 요청이 있습니다.

일일이 사진을 웹 에디터로 작성을 하기는 불편하다. 드래그 앤 드롭으로 이미지를 쉽게 작업하게 

되었으면 좋겠다는 의견이 있습니다.

**Comment by baemoc** [comment]
#151

**Comment by baemoc** [comment]
다중 이미지 업로드로 대체함.
