### ISSUE TITLE
뉴스 메인 페이지에서 제목이 찔리는 문제

### ISSUE THREAD

**Issue by jejoongkim** [netnamu/zinpack#59]
제목이 찔리지 않게
서울 강남에서 김길동씨 발등을 차에 찍혀
서울 강남에서 김길동씨 발......
과 같이 되면 곤란하다는 의견

**Comment by leihaht** [comment]
마우스를 올렸을때 Tooltip 나오게 하는방법이 있습니다.

아니면 리스트의 컨텐츠를 클릭했을때 Modal 형식으로 간략한 컨텐츠 정보를 보여주게하고 거기에서 클릭하면 실제 컨텐츠 페이지로 이동하게 하는 방법도 있습니다.

**Comment by jejoongkim** [comment]
현재 taxfinance.kr 페이지를 보면 토픽 박스 안의 제목이 10자 정도로 너무 짧아서 내용 파악이 되지 않습니다. 제목만 보고 클릭을 유도 해야 하는데 그렇지 않은 듯 합니다.
차라리 내용 앞 부분 보이는걸 없애고 제목을 20자 정도로 보이게 하던지, 최이사님 의견을 반영하던지 해야 할 듯 합니다.

**Comment by leihaht** [comment]
확실히 그 부분에서의 제목은 너무 짧네요.
그렇다고 긴 제목을 전부 보여주기에는 레이아웃이 어긋날수도 있습니다.

현제 제목 글자 수는 서버에서 제한하고 있는것으로 알고있습니다만, 추후에 글자수는 front-end에서 조절하는 방법을 써야될듯하네요.

그리고 지금 이 문제를 해결하려면 tooltip으로 쓰는걸 추천드립니다.

**Comment by baemoc** [comment]
다보여주게 하기 위해서는 레이아웃에서  쌓기 로 설정하는 방법으로 해결 하는건 어떤가요?

**Comment by leihaht** [comment]
레이아웃에서 쌓기로 설정하는 방법이 무슨말씀이신지 이해가 안되네요.

**Comment by baemoc** [comment]
현재 리스트가 3단과 6단에는 Masonry 방식으로 되어 있습니다.
Masonry에는 제목이 길게도 들어갈 수 있네요.
2단에서는 제목을 짤리는 그대로 두고, 3/6단만 제목 전체를 보여주는게 어떨지요.

**Comment by jejoongkim** [comment]
3단 6단에서 제목 전체를 보여주는것......너무 길면 역시나 짤리겠지만. 배이사님 의견을 한번 데모해보고 판단해보시는건 어떨까요? 현재는 대략 14자 정도 보여주는데 확실히 짧긴 하네요..배이사님 의견대로 조정을 해보고 그리고 업체들의 인식도 교육을 해서 적당한 제목내에 표현을 할 수 있도록 동시에 진행을 해보면 좋겠습니다.

**Comment by leihaht** [comment]
제목이 짤리고 안 짤리고는 특별히 문제가 아니라고 봅니다.
제 입장에서 정작 문제가되는것은 box 높이가 유동성있게 변하느냐 아니면 고정되느냐인데요.
box 높이가 유동성있게 변하게되면 column들이 6칸일때 그것들의 높이를 맞춰줘야 정렬되보이고, 안그러면 다음줄에 들어갈 box가 다음으로 높이가 낮은 box 밑으로 들어가게되있죠.
masonry 시스템은 이러한 쌓기? 식으로 레이아웃이 만들어집니다.

Pinterest.com 같은식의 레이아웃이 그 대표적인 예이죠.
그러나 이러한 레이아웃은 자칫 정렬되보이지않는 느낌을 줄때가 있죠.
쇼핑몰 사이트들은 정렬된 방식의 레이아웃을 많이 쓰이죠.
box 높이가 전부 일정하다면 특별한 조작없이 정렬된 레이아웃으로 자동으로 만들어집니다.

결국, 제목이 좀더 길게 나와야된다면 제목 글자수를 조절하는것도 좋지만, box의 높이를 조절하는것도 한 방법입니다.

아무래도 제목길이가 너무 짧다는 이슈가 많이 들어오는걸보니 box 높이를 조절해야겠다는 생각이 드네요.

**Comment by baemoc** [comment]
제목 길이 부분은 해결한 것으로 보입니다.
