### ISSUE TITLE
조회수와 별개의 추천 기능 필요

### ISSUE THREAD

**Issue by jejoongkim** [netnamu/zinpack#60]
커뮤니티 중심 운영할때 추천 기능 필요 의견

**Comment by aeroitems** [comment]
좋아요 기능을 추가

**Comment by aeroitems** [comment]
추천 기능은 게시물과 댓글에 모두 적용
댓글은 베스트 댓글을 최대 3개 까지 표시
베스트 댓글은 최소 3번 이상의 추천을 받아야 됨
추천은 한 게시물에 1인 1일 1회 만 가능
여러 게시물에 추천은 제약 없이 가능

**Comment by baemoc** [comment]
추천 버튼은 sns공유 버튼 옆에 있습니다.
동일한 게시물은 한번  추천하고 24시간이 지나면 다시 추천할 수 있습니다.
댓글의 경우 첫 댓글에만 추천기능이 있습니다.
(댓글의 댓글은 추천이 없음)
베스트 댓글은 추천수가 3회 이상인 댓글의 1/2/3위만 노출됩니다.
