### ISSUE TITLE
청소년 결제 수단 부재

### ISSUE THREAD

**Issue by jejoongkim** [netnamu/zinpack#61]
청소년 결제시 현금이체가 가능한지
안된다면 가상결제통한 무통장입금방식, 상품권 결제 방식이 필요

청소년은 신용카드도 없고 모바일결재도 할 수 없는 경우가 많음    앨로 페이, 카카오페이, 애플 페이 등이 이런 것을 지원한다면 이들을 활용하는 것은 어떠할지

**Comment by baemoc** [comment]
이번에는 가상결제만 진행합니다.
알리페이나 카카오, 애플은 향후 검토를 필요로 합니다.

**Comment by baemoc** [comment]
가상계좌 서비스 신청 후, 개발 가능합니다.

**Comment by aeroitems** [comment]
서비스  신청 서류 접수 후 2주가량 소요된다고 합니다.

**Comment by jejoongkim** [comment]
수고하셨습니다.

**Comment by baemoc** [comment]
가상계좌 심사완료 되었습니다.
이번 개발일정에 개발토록 하겠습니다.

**Comment by baemoc** [comment]
가상계좌 셋팅 완료되었습니다.
PC와 모바일 테스트도 해봤습니다.
1. 포인트 결제
   가상계좌를 사용하면 포인트내역에 노출은 되나, 실제 포인트는 입금과 동시에 적용됨.
   포인트내역에 '입금대기' 버튼을 누르면 계좌번호 나옴.
   입금이 완료되면, '영수증'으로 바뀜.
2. 영수증 : 카드는 카드영수증이 나오고, 가상계좌는 입금내역이 나옵니다.( LG U+ 제공)
3. 쇼핑몰 결제
   구매내역에 '입금대기'로 노출됨.
   입금 완료시, 주문으로 변경됨.
