### ISSUE TITLE
그룹 가입 메시지 변경 제안

### ISSUE THREAD

**Issue by jejoongkim** [netnamu/zinpack#65]
그룹에 가입하시겠습니까? --> 확인...이렇게 진행 되는데  
그룹에 가입한다는 말이 익숙치 않은 듯 합니다.

해당 포럼, 게시판, 모임, 이야기방, 등등으로 안내 메시지를 변경하는게 접근성에 더 좋을 듯 합니다.

이야기방에 가입(참여) 하겠습니까?

**Comment by baemoc** [comment]
이건 어떻게 할까요?

**Comment by jejoongkim** [comment]
현재 게시판 활용 기능이 있으므로 이 건 차후에 논의해도 될 듯 합니다.
