### ISSUE TITLE
브로마이드 싸이트 제목에 W/ 이런 표시가 나오는 이유?

### ISSUE THREAD

**Issue by jejoongkim** [netnamu/zinpack#67]
제목에 WW 같은게 나오는 이유는?

**Comment by aeroitems** [comment]
제목에 특수 기호 따옴표와 외따옴표를 사용할 경우 나타나는 현상으로 프로그램에서 수정가능

**Comment by baemoc** [comment]
큰따옴표와 작은따옴표의 경우 DB에 저장할 때, 역슬래시를 같이 넣어줍니다.
출력할때, &#039 &quot 이런형식으로 변경하여 출력하도록 변경하였습니다.
공지사항, 소개, 뉴스, 쇼핑몰, 컨텐츠몰 제목 모두 따옴표 사용 가능합니다.

**Comment by baemoc** [comment]
토픽이나 리스트, 상세보기 등에서 잘 나오는지 테스트 부탁드립니다^^

**Comment by baemoc** [comment]
댓글에도 따옴표와 작은따옴표 사용가능.

**Comment by jejoongkim** [comment]
토픽에  w 표시 나옵니다.
테스트 페이지 랜딩페이지 토픽에 현재 오류난 상태로 놔두었습니다. 배너도 같습니다.

**Comment by baemoc** [comment]
수정하였습니다.
