### ISSUE TITLE
게시판에 글 쓸때 간편모드에서 이미지+가 무조건 들어가 있지 않게?

### ISSUE THREAD

**Issue by jejoongkim** [netnamu/zinpack#70]
이미지 + 가 디폴트로 들어가 있는데
그냥 이미지 업로드 버튼만 있으면 안되는지? 대부분 게시물에는 글을 쓰게 되는데 이미지를 안 올리면 안되는줄 알게 됨.  - 를 누루면 안 올려도 되는 것을 처음에 잘 모름

**Comment by aeroitems** [comment]
디폴트로 이미지 첨부가 없는 상태로 설정.
- 버튼을 눌러 이미지 첨부를 추가해야 이미지를 넣을 수 있게 수정

**Comment by jejoongkim** [comment]
테스트 페이지서 테스트 완료. 이미지 없이도 글 잘써지능~
