### ISSUE TITLE
각 그룹의 메인 단추를 설정 가능하면 좋겠음

### ISSUE THREAD

**Issue by jejoongkim** [netnamu/zinpack#71]
토크 그룹에서도 메인을 누르면 브로마이드 본 싸이트로 이동이 되어야 함.

메인 단추를 경로 설정 가능토록 되었으면 좋겠슴.

토크로 들어갔다가 다시 본 싸이트로 이동하는 경로가 애매함. 아니면 맨 위 헤드라인 이미지에 경로를 설정 가능토록 하여야  할 듯

**Comment by aeroitems** [comment]
버튼의 명칭을 변경해서 해결하는 방법으로 가이드 해야할 것으로 보입니다.

**Comment by aeroitems** [comment]
상단 메뉴를 처음 부터 모든 버튼을 등록 가능하도록 수정
예를 들어 기본으로 나오는 Main 버튼도 지정하여 넣고 삭제하거나 수정할 수 있는 기능 추가

**Comment by baemoc** [comment]
[관리자 > 뉴스 > 분류관리] 
기존의 대/중/소 분류에서 단일 분류로 변경됨.
하나의 게시판을 생성한다고 생각하면 쉬움.
관리자가 알아볼수 있는 분류명과 권한만 설정가능.
(쇼핑/컨텐츠/이북 동일)

[관리자 > 메인 > 상단메뉴 관리]
기존 방식과 다르게 하위메뉴를 뉴스/쇼핑/이북/컨텐츠 섞어서 쓸수 있음. 
현재 메뉴가 뉴스/쇼핑/이북/컨텐츠 게시판인지 판별하여 오른쪽 위의 글쓰기, 장바구니 등 버튼이 바뀜.
(메뉴는 4단까지 가능하며, 메뉴저장 버튼으로 저장가능.)
1.종류
뉴스/쇼핑/이북/컨텐츠 - 메뉴 자체가 게시판
분류(목록) - 게시판은 아니나 하위메뉴의 게시판을 합쳐서 보여줌.
분류(비노출) - 하위메뉴를 펼치기위한 도구.
링크 - 해당URL로 이동.
메인 - 랜딩페이지로 이동.
2.분류 = 쇼핑/이북/컨텐츠/뉴스 의 게시판 목록.
3.리스트형식 = 메뉴마다 2단/3단/6단 등의 리스트형식 지정.
4.슬라이드 = 메뉴마다 10개씩 슬라이드 노출가능.
5.배너&인기글 = 메뉴마다 10개씩 배너 노출가능. (레이아웃상 인기글과 공지사항은 기본으로 딸려감.)

[관리자 > 디자인설정 > 기본설정]
시작페이지 = 랜딩페이지가 기본으로 존재하며,
상단메뉴를 만들어 놓으면 링크와 비노출분류를 제외하고 선택가능.

[기타]
1. 기존의 각각의 메인 페이지와 리스트 페이지를 하나의 페이지로 통합함.
2.쇼핑몰의 경우 그룹에서 분류와 상품등록이 되도록 변경.
3.관리자페이지 왼쪽상단 4개버튼이 쓸모가 없어짐.(회의필요)
4. RSS의 경우, 뉴스만 보여줄 것인지/메뉴에 포함된 샵/컨텐츠/이북까지 보여줄건지? (회의필요)
5. 메인랜딩 페이지의 슬라이드를 직접 등록하게 하는게 좋은거라 판단됨.(회의 필요)

[테스트 요청사항]
1. 뉴스/쇼핑/이북/컨텐츠 각각 분류를 생성/수정/삭제
2. 상단메뉴를 옵션을 전부 써가며 생성/수정/삭제
3. 메뉴와 분류가 바뀌었으므로, 뉴스/쇼핑/이북/컨텐츠에 각각 컨텐츠를 등록하고 승인한 뒤 노출확인.
4. 쇼핑몰의 경우, 그룹에서도 상품등록 및 결제 확인바람.(실제 결제는 되지 않음)
5. 이번 업데이트는 거의 전체가 다 바뀌어서 사실상 모든 페이지를 다 테스트해야 합니다.

**Comment by baemoc** [comment]
1. RSS의 경우현재 메뉴에 대응하여 변경하였습니다.
   (뉴스와 기타 섹션이 섞여 있어도 뉴스만 나오도록 했습니다.)
2. 인기글의 경우 조회수가 매월 초기화됩니다.
3. 분류(목록)에 하위메뉴가 없어도 오류가 나지 않도록 변경하였습니다.
4. 브로마이드의 경우, 그룹의 글과 댓글을 사이트로 이동할수 있도록 준비해놨습니다.

**Comment by baemoc** [comment]
메인랜딩페이지의 슬라이드를 직접 등록하도록 변경하였습니다.
관리자 > 메인 > 슬라이드 관리  에서 설정가능.
