### ISSUE TITLE
게시물의 댓글 수 표시하기

### ISSUE THREAD

**Issue by aeroitems** [netnamu/zinpack#72]
게시물에 댓글이 몇개 달렸는지 표시 필요

**Comment by baemoc** [comment]
뉴스,쇼핑몰,컨텐츠몰,이북몰의 리스트/상세뷰/검색리스트/메인에 총 댓글수 추가.

**Comment by jejoongkim** [comment]
댓글에 추천기능 테스트완료...ㅋㅋ 근데....내 댓글에 내가 무한 추천을 날릴수 있다능?
