### ISSUE TITLE
뉴스보드와 별개의 게시판 필요

### ISSUE THREAD

**Issue by jejoongkim** [netnamu/zinpack#75]
지금까지는 그룹 기능을 변칙적으로 활용해서 게시판을 만들어서 사용하도록 했습니다.

그러나 그렇게 하기에는 한계가 있는 듯 합니다. 관리자가  그룹마다 본래 홈페이지와 비슷하도록 디자인을 일일이 적용하기도 불편하고, 잡지사가 주체가 되는 홈페이지인데 본래 홈페이지랑 그룹이 연계가 전혀 안됩니다. 원래 처음에 그리 하려고 기획했었기 때문이긴 하지만, 지금 마케팅 방향하고는 맞지 않습니다. (그룹을 게시판으로 활용하는 것)    그룹기능은 유지하여 차후 그룹을 신청/승인해서 쓰게 하더라도 그것과는 별개로 뉴스 보드 외의 독립적인 게시판(댓글, 조회 등이 가능한)이 필요합니다. 지금은 급한대로 적응들을 시켜 활용하게 하더라도 3.0버전에는 게시판을 자유롭게 추가 삭제할 수 있도록 해야 할 거로 생각합니다.

**Comment by baemoc** [comment]
상단 메뉴의 변경으로 해결된것으로 보입니다.
