### ISSUE TITLE
마우스 오른 클릭 제한의 건

### ISSUE THREAD

**Issue by jejoongkim** [netnamu/zinpack#78]
이미지와 콘텐츠 마우스 오른 클릭 복제를 제한해 달라는 니즈가 있습니다.

캡쳐를 하는 것과 마우스 클릭으로 이미지 자체를 복제 하는 것에는 엄연한 차이가 있다.

이미지 자체가 해상도가 높은 이미지가 기사에 들어가므로 무한 복제를 허용하는 것은 반대합니다.

마우스 오른 클릭을 통한 복제를 막아 주십시오   - 모터매거진, 월간 퍼블릭아트  제안

**Comment by aeroitems** [comment]
마우스 오른쪽 클릭 기능 제한은 필요하다고 봅니다.
자동 워터마크 기능도 필요하긴 하죠. 

방법을 찾아 봐야겠네요.

하지만 해상도가 높은 이미지를 뉴스게시판에 올리는 것은 별로 좋은 방법이 아니라고 보여집니다. 트래픽과 용량을 줄여야하는 운영상의 숙제가 있으므로 이미지는 가능한 줄여야 합니다.
그리고 요즘 소셜로 포워딩 스크랩을 지원하는데 이미지를 프로텍션 하겠다는 것은 모순적이라고 생각됩니다. 그래서 각 보도자료를 만드는 일간지 뉴스들은 이미지에 워터마크를 넣고 있는 것입니다.

출처가 어디인지는 밝히되 프로텍션은 하지 않는다는 것이 지금 인터넷 매채들의 기본 속성이고 방향입니다. 

그리고 마우스 오른쪽 클릭 아무리 막아봐야 아이패드나 아이폰/안드로이드 폰 같은 모바일 디바이스에서 이미지 저장하는데에는 아무런 막을 방법이 없습니다. 오른쪽 버튼 프로텍션 보다는 워터마크를 넣는 것이 좋은 해결 방안이라고 보여집니다.

**Comment by jejoongkim** [comment]
캡쳐를 하는 것은 어쩔수 없지만 캡쳐 이미지와 원본 이미지는 차이가 있다. 그리고 일일이 들어가는 이미지를 모두 워터마크 작업을 할 여유는 없다. 아예 이미지 저장 자체를 막는 것이 필요하다는 의견 입니다.

**Comment by baemoc** [comment]
관리자 페이지를 제외한 모든 페이지에
마우스 오른쪽 클릭/드래그/복사 를 막았습니다.

**Comment by jejoongkim** [comment]
테스트 완료 했습ㄴ이다. 클로즈 합니다
