### ISSUE TITLE
간편모드와 편집모드의 호환성 지원

### ISSUE THREAD

**Issue by jejoongkim** [netnamu/zinpack#79]
간편 모드로 현장에서 기사를 올렸더라고 추후 다시 편집을 할 필요가 있는데 일일이 카피하고 이미지를 다시 다운르도해서 재 편집하기가 불편하다.
간편모드로 일단 올라온 내용을 바로 에디터 편집모드에서 수정, 편집할 필요가 있다.

-월간 그라피, 월간 모터매거진, 월간 브로마이드 제안 내용

**Comment by baemoc** [comment]
간편모드 -> 에디터 는 가능할 것 같구요.
에디터 -> 간편모드는 불가능합니다.

**Comment by baemoc** [comment]
간편모드로 저장하면 에디터로 변경이 가능합니다.
유튜브가 있으면 제일 상단에 iframe으로 삽입되고,
첨부했던 1~10개의 이미지가 차례대로 삽입됩니다.
그리고 제일 밑에 기본내용이 삽입됩니다.

한번 에디터로 저장하면 간편모드로 돌아오지 못합니다.

**Comment by jejoongkim** [comment]
간편보드로 동영상 삽입 후 에디터 모 드로 변경후 다시 편집해보는 테스트 완료 했습니다.
훌륭합니다.
