### ISSUE TITLE
뉴스의 경우, PC화면에서 좌우여백을 설정하는 옵션

### ISSUE THREAD

**Issue by baemoc** [netnamu/zinpack#80]
뉴스 컨텐츠의 전체의 여백을 잡느냐?
이미지는 100%로 두고 글만 여백을 잡느냐?

반응형으로  PC에서만 여백이 생기도록 해야하기 때문에
최이사님께서 class를 하나 만들어주시면 감사하겠습니다^^
여백 옵션을 on 하면 class를 넣고 off면 넣지 않는식으로 만드는게 좋을 것 같습니다.

**Comment by leihaht** [comment]
여백이 margin을 말씀하시는건지 padding을 말씀하시는건지 잘 모르겠네요.

죄송하시만 이해가 안갑니다. 좀더 구체적으로 설명 부탁드립니다.

**Comment by baemoc** [comment]
이부분은 박이사님과 상의하셔야 할것 같습니다.

**Comment by aeroitems** [comment]
![dd01](https://cloud.githubusercontent.com/assets/8153667/4714982/9151c164-58f9-11e4-95a3-a6fa545b9552.jpg)

이 화면을 아래 화면처럼 정렬 되도록 하는 옵션을 넣었으면 합니다.
이에 관련된 클래스를 만들어 주시면 될듯 합니다.

![dd02](https://cloud.githubusercontent.com/assets/8153667/4714990/af170024-58f9-11e4-9d35-2921a2c8fec9.jpg)

**Comment by baemoc** [comment]
뉴스의 글쓰기 및 수정에 '좌우여백'이라는 옵션을 추가하였습니다.

**Comment by jejoongkim** [comment]
훌륭합니다. 테스트 해봤습니다.

**Comment by leihaht** [comment]
적용한 css 이메일로 보내드렸습니다.

**Comment by jejoongkim** [comment]
테스트 페이지에서 테스트 했습니다.
