### ISSUE TITLE
pdf 이북 등록시 오류가 남

### ISSUE THREAD

**Issue by jejoongkim** [netnamu/zinpack#83]
pdf 형식의 이북 등록시 1.8%에서 멈춥니다. 최적의 페이지수, 용량에 대한 검증이 필요합니다.

**Comment by baemoc** [comment]
100페이지 넘는 PDF를 넣었는데 잘됩니다.
PDF 자체의 문제 같습니다.

**Comment by jejoongkim** [comment]
pdf 등록 테스트를 하였습니다.  BRITAN 40메가 100페이지 짜리 잘 올라감을 확인 했습니다. 그러나 해상도가 많이 떨어집니다. 해상도를 높이기 위해 고급으로 작업을 해야하는 군요
