### ISSUE TITLE
업데이트 이후 뉴스 보드에 새로운 뉴스가 노출이 안됩니다.

### ISSUE THREAD

**Issue by jejoongkim** [netnamu/zinpack#84]
새로운 ㄴ뉴스를 제대하고 저장했으나

뉴스 페이지 해당 카테고리 안에서 보이지를 않습니다.

단 관리모드에서 - 전체뉴스 조회를 해보면 뉴스는 있으나 노출은 안됩니다.

**Comment by jejoongkim** [comment]
수정 확인 하였습니다.

**Comment by baemoc** [comment]
해당글은 저장되었으나, 리스트를 보여주는 데이타에 저장이 잘못된 오류였습니다.

**Comment by baemoc** [comment]
관리자페이지의 뉴스,컨텐츠,쇼핑,이북의 전체보기에서 카테고리명 오류수정.
뉴스,컨텐츠,쇼핑,이북의 전체보기에서 리스트에 닉네임 추가.
