### ISSUE TITLE
관리자가 게시물을 수정 할 수가 없습니다.

### ISSUE THREAD

**Issue by jejoongkim** [netnamu/zinpack#85]
수정 하는 권한이 있어야 되는지 여부를 논의 후  필요하다면 ....

**Comment by baemoc** [comment]
관리자는 모든 뉴스게시물의 수정이 가능하고, 글쓴이는 자신의 게시물의 수정이 가능합니다.
관리자페이지에 해당 게시물로 이동하는 링크를 걸어두겠습니다.
링크로 이동하면, 상단메뉴와 상관없이 해당글로 이동가능합니다.
그곳에서 수정해주시면 되겠습니다.

추가사항 : 글쓴이도 관리자페이지에서 자신의 뉴스 전체를 볼수 있게 함.

**Comment by jejoongkim** [comment]
감사합니다. 수고하셨습니다.

**Comment by jejoongkim** [comment]
관리자가 관리모드에서 전체 뉴스를 조회하고 해당 뉴스로 바로가기 한 다음

수정 혹은 삭제할 수 있는 권한을...테스트 페이지에서 테스트 했습니다.
