### ISSUE TITLE
토픽과 배너를 섞어서 배치

### ISSUE THREAD

**Issue by baemoc** [netnamu/zinpack#86]
랜딩페이지와 뉴스,컨텐츠,쇼핑,이북의 본문에 있는 토픽과 배너를 섞어서 보여주는 기능
토픽과 배너에 들어가는 컨텐츠들은 상단메뉴 안에서 선택가능.

현재는 토픽과 배너의 가로세로사이즈가 일치하지 않아 수정이 필요함.

**Comment by aeroitems** [comment]
정사각형 배너의 추가가 필요합니다. 내부에 글이 들어가는 것과 글이 들어가지 않는 것에 대한 최이사님의 디자인 가이드가 필요합니다.

**Comment by aeroitems** [comment]
사이즈 규격
배너 : 
1단x1줄, 2단x1줄, 3단x1줄, 4단x1줄, 5단x1줄, 6단x1줄
1단x2줄, 2단x2줄, 3단x2줄, 4단x2줄, 5단x2줄, 6단x2줄

토픽 : 
2단x2줄, 3단x2줄

**Comment by baemoc** [comment]
스크랩 이라는 명칭으로 추가.
슬라이드/토픽/배너 3가지를 무한대로 섞어서 추가 가능.
분류에서 선택할 경우, 최신/인기/무작위 순으로 정렬 가능.
1. 슬라이드
   @ 직접 이미지 등록(최대 10개)
   @ 크기 설정 불가
2. 배너
   @ 직접 등록(최대 10개), 분류에서 선택
   @ 크기 : 1칸x1줄, 2칸x1줄, 3칸x1줄, 4칸x1줄, 5칸x1줄, 6칸x1줄, 1칸x2줄, 2칸x2줄, 3칸x2줄, 4칸x2줄, 5칸x2줄, 6칸x2줄
   @ 색상지정 : 박스배경
3. 토픽
   @ 직접 등록(최대 3개), 분류 선택, 공지사항
   @ 크기 : 2칸x2줄, 3칸x2줄
   @ 색상지정 : 박스배경,투명도,글자색상,글자 마우스오버 색상

1.랜딩페이지 : 관리자 > 메인 > 스크랩 설정 에서 수정 가능
2.리스트페이지 : 상단메뉴관리 에서 메뉴 수정 들어가시면, 메인스크랩 노출
(노출되면, 상단메뉴관리 리스트에 폴더아이콘 생성)
3.본문페이지 : 상단메뉴관리 에서 메뉴 수정 들어가시면, 본문스크랩 노출
(노출되면, 상단메뉴관리 리스트에 종이(?)아이콘 생성)

★ 업데이트 후에, 각 사이트 랜딩페이지와 리스트 페이지 수정 바랍니다.
리스트의 공지사항은 없어지고 배너를 임의로 넣었습니다.
본문에 들어가던 토픽은 다 사라집니다. 메뉴별로 추가하시면 됩니다.

**Comment by baemoc** [comment]
본문스크랩은 쇼핑/뉴스/컨텐츠/이북 일 경우에만 삽입할 수 있습니다.

**Comment by baemoc** [comment]
배너와 슬라이드의 경우 가로x세로(px) 크기를 추가적으로 넣었습니다.
