### ISSUE TITLE
상품 등록시 요청하기 누르면 ' 잘못된 접근 입니다' 메시지 나옵니다

### ISSUE THREAD

**Issue by jejoongkim** [netnamu/zinpack#87]
상품을 등록후 승인을 신청하기 위해 요청하기를 누르면 ' 잘못된 접근입니다' 라고 나옵니다.

그리고 승인요청이 접수 되지 않습니다.

**Comment by baemoc** [comment]
페이지의 권한에 대한 오류였습니다. 수정완료!
