### ISSUE TITLE
구매영수증 출력 기능

### ISSUE THREAD

**Issue by aeroitems** [netnamu/zinpack#88]
구매 영수증을 출력할 수 있는 기능이 필요합니다.
안되면 구매 영수증을 출력할 수 있는 LG U+ 사이트 링크라도 만들어 주세요...

**Comment by baemoc** [comment]
휴대폰 결제의 경우 영수증이 어떻게 나오는지 확인을 하지 못했습니다.
일단 테스트 사이트에 적용하였고, 버전 업데이트 하고 확인해야 하겠습니다.

**Comment by baemoc** [comment]
카드결제의 경우 카드명세서가 나오고
가상계좌의 경우 입금내역이 나오고, 거기서 주문번호를 누르면 무통장 거래내역 확인증이 나오네요^^

**Comment by baemoc** [comment]
2.4.10 적용하고 추가적으로 아래 영수증 확인하였습니다.
휴대폰 결제 : 휴대폰결제 거래내역 확인서
계좌이체 : 계좌이체 거래내역 확인서
