### ISSUE TITLE
이북 등록시 따옴표 등을 넣으면 특수문자나 역슬래시 등으로 표현됨

### ISSUE THREAD

**Issue by aeroitems** [netnamu/zinpack#91]
이북에 본문이나 제목에 인용 부호를 넣으면 역슬래시가 포함된 특수기호 표시 방식으로 바꿔나타나는 현상이 생긴다고 합니다.
확인 바래요...

**Comment by baemoc** [comment]
이북 내부의 따옴표 수정하였습니다.
