### ISSUE TITLE
페이스북에 스크랩시 기호들이 사라지는 문제

### ISSUE THREAD

**Issue by aeroitems** [netnamu/zinpack#93]
게시물에서 페이스북 공유하기를 누르면 제목에 기호(물음표, 느낌표, 따옴표 등)가 사라지는 문제가 있네요. 나타나게할 방법이 없을지요?

**Comment by baemoc** [comment]
페이스북은 url이 아니어서 가능합니다.
그 외의 다른 공유하기는 URL방식이라 특수문자 전송이 안되네요
