### ISSUE TITLE
이북 판매시 판매자 ID로 포인트 적립이 안됨

### ISSUE THREAD

**Issue by aeroitems** [netnamu/zinpack#96]
이북 판매되면 이북을 올린 사람 ID로 포인트가 적립되지 않네요.
원래 판매되면 즉시 적립되는 시스템 아니었나요? ^_^;
기억이 가물해서...

**Comment by baemoc** [comment]
추가 및 예정 사항입니다.
1. [슈퍼 > 사이트관리] 에서 이북/컨텐츠 판매금액을 인포웨이 / 사이트 / 판매자가 어떠한 비율로 나눠가질지 설정
2. 뉴스/이북/컨텐츠  포인트 후원(선물) 시, 판매자 ID에 100%  포인트 적립.
3. 이북/컨텐츠 판매시, 판매자와 사이트 ID에 설정한 비율로 포인트 적립.
4. [관리자페이지 >  정산관리 > 정산] 기능 제거.
5. 포인트로 판매된 금액은 [관리자페이지 >  정산관리 > 환전] 에서 신청시에만, 익월에 정산함.
(쇼핑몰과는 다르게 자동으로 정산해주지 않음)

회의 필요
1. 환전 시, 수수료율을 얼마로 할것인지?
2. 환전해주는 날짜는 몇일로 할 것인지?

**Comment by baemoc** [comment]
1. 판매된 금액을 나누기 위해서 포인트를 소수점 2째자리까지로 변경.
2. [슈퍼 > 정산관리 > 포인트 환율] 에서 몇 포인트당 몇 원(현금)으로 환전 가능한지 설정.
3. 환전은 2번에서 설정해놓은 금액으로만 신청가능.
   (사용자가 100포인트를 가지고 있고,  20포인트로 설정되어있을 경우, 20포인트로 5번 환전 신청)

**Comment by baemoc** [comment]
익월 신청시, 이월 15일에 입금하셔야 합니다.
입금하실 내역은 [슈퍼 > 환전내역]에서 날짜별로 뽑으실 수 있구요.
입금하시고, 입금완료 승인을 해주셔야 합니다.
