### ISSUE TITLE
토픽 직접등록에서 URL 입력해도 저장이 되지 않음

### ISSUE THREAD

**Issue by jejoongkim** [netnamu/zinpack#97]
토픽이나 배너 직접입력 선택하고

하단에 배너 입력하고...수정하기 버튼을 누른 이후 

다시 들어가 보면...URL이 저장되어 있지 않습니다.

**Comment by baemoc** [comment]
변수 처리가 제대로 이루어지고 있지 않았습니다.
수정하였습니다.

**Comment by jejoongkim** [comment]
테스트 했습니다. 잘 됩니다.
