### ISSUE TITLE
본문 안에 토픽박스, 배너 설정하는 메뉴가 없습니다.

### ISSUE THREAD

**Issue by jejoongkim** [netnamu/zinpack#98]
본문내 스크래퍼 설정?

암튼..기사 안에 들어가서 하단에 있는 토픽,배너 박스 설정하는 메뉴가 어디에 있는지?

**Comment by baemoc** [comment]
1.랜딩페이지 : 관리자 > 디자인 설정> 메인화면 설정 에서 수정 가능
2.목록 스크래퍼, 본문 스크래퍼
관리자 > 디자인 설정> 상단메뉴 설정
메뉴 추가 또는 수정 > 목록 스크래퍼 노출, 본문 스크래퍼 노출
목록은 폴더아이콘 생성, 본문은 종이모양 아이콘 생성
아이콘 클릭시 스크래퍼 설정페이지로 이동

**Comment by baemoc** [comment]
본문 스크래퍼의 경우는, 게시판일 경우만 나타납니다.
링크나 분류 등에는 나타나지 않습니다.

**Comment by jejoongkim** [comment]
찾았습니다.
